### ISSUE TITLE
allow char[] for password field type

### ISSUE THREAD

**Issue by makkus** [cbeust/jcommander#118]
Not sure whether it'd be easy to do and whether it makes sense for JCommander at all, but in general it'd be good if the password field type could also be a char[]. 

For most of my code, I find it a good practice to use char[] instead of Strings for those fields because I can actually remove them from memory (something like, Arrays.fill(pw, 'x')) before they get garbage collected. For Strings, this is not possible and they might linger on until collection time. 

Agreed, only a small improvement in security since you're probably screwed anyway if somebody reads your memory, but still...

**Comment by jeremysolarz** [comment]
@cbeust very old. Your opinion?
