### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by Raos123** [cbeust/jcommander#121]
Right now if you forget to enter a value for an option the parser does not catch that.
If another option follows, then it just uses that as the value.
Worst case if it is at the end of the arguments list and indexOutOfBounds error occurs since it assumes there is a value.

examples:
 -u -v
 -v

**Comment by jeremysolarz** [comment]
@cbeust looks like this is still an error

Test case: 
```
@Test
  public void missingValueForParameter(){
      class A {
        @Parameter(names="-u")
        String u;
        @Parameter(names="-v")
        String v;
      }

      A a = new A();
    JCommander jCommander = new JCommander(a);
    jCommander.parse("-u", "-v");
    System.out.println(a.u);
  }
```

**Comment by jeremysolarz** [comment]
@cbeust what do you say, looks like it might be a bit hairy to fix. 😄

**Comment by cbeust** [comment]
I'd say it's working as intended. Options can start with any character, so `-v` might be a legitimate argument to the `-u` option.

**Comment by jeremysolarz** [comment]
Understood. Do you think it makes sense if we mention it in the docs that `JCommander` is in this sense _greedy_? 😃
