### ISSUE TITLE
List parameters parsing error

### ISSUE THREAD

**Issue by sas84** [cbeust/jcommander#145]
Failed to parse list parameters if parameter have multiple names.

jCommander version 1.30

@Parameter(names = {"-instance", "-ins"}, description = "Instance ID")
    private List<String> instances = new LinkedList<String>();

"-ins i01 -ins i02"  - OK, two entries in the list
"-instance i01 -instance i02"  - OK, two entries in the list
"-instance i01 -ins i02" - FAIL, only i02 in the list
"-ins i01 -instance i02" - FAIL, only i02 in the list

**Comment by jeremysolarz** [comment]
Works both in latest. Closing.

```
@Test
    public void list(){
      class Cmd {
        @Parameter(names = {"-instance", "-ins"}, description = "Instance ID")
        private List instances = new LinkedList();
      }
      Cmd cmd = new Cmd();
      JCommander.newBuilder()
              .addObject(cmd)
              .args(new String[]{"-ins","i01","-instance","i02"})
              .build();
      Assert.assertEquals(cmd.instances.size(), 2);


      Cmd cmd2 = new Cmd();
      JCommander.newBuilder()
              .addObject(cmd2)
              .args(new String[]{"-instance","i01","-ins","i02"})
              .build();
      Assert.assertEquals(cmd2.instances.size(), 2);
    }
```
