### ISSUE TITLE
Stop removing double quotes when parsing arguments.

### ISSUE THREAD

**Issue by tobiasbertelsendeltek** [cbeust/jcommander#153]
**Problem in short**
JCommander removes quotes. (JCommander.java line 501).
The shell is removing quotes that surrounds arguments, so when JCommander does this, it invalidates the string.

**Problem, explained**
I have a parameter which contains multiple strings, each surrounded by quotes. e.g. `"string one" "string two"`.
I put this on the command line escaping the quotes, like this:
`"\"string one\" \"string two\""`
The shell parses this perfectly fine, so I get the correct string as a value in `String args[]`. When JCommand parses this string it removes the outer quotes, so it becomses `string one" "string two`. When this is later interpreted, it gets interpreted as three strings: `string` and `one string` and `two`.

**Solution**
Delete line 500-502. Alternatively hide it behind a flag, so users can turn it on/off themselves.

**Comment by deric** [comment]
Here's reference to the [code for removing quotes](https://github.com/cbeust/jcommander/commit/94e08e73342f858518b14a70624c38479c0365d3#diff-b658a3c4420af2b046c522979a5973beR500).

Is there some workaround how to escape separator (e.g. whitespace)? I would like to use something like:
```
--arg "foo bar"
```
without changing separator.

**Comment by RuedigerMoeller** [comment]
also have this issue

**Comment by jeremysolarz** [comment]
This works with latest release. Closing.

```
@Test
  public void quoted(){
    class Cmd {
      @Parameter(names = {"-instance", "-ins"}, required = true, description = "Instance ID")
      private List<String> instances = new LinkedList();
    }
    Cmd cmd = new Cmd();
    JCommander.newBuilder()
            .addObject(cmd)
            .args(new String[]{"-ins", "\"string one\"","-ins",  "\"string two\""})
            .build();
    Assert.assertEquals(cmd.instances.size(), 2);
  }
```
