### ISSUE TITLE
Update CHANGELOG file with version 1.31 and 1.32.

### ISSUE THREAD

**Issue by garydgregory** [cbeust/jcommander#167]
Please update the CHANGELOG file with version 1.31 and 1.32.

**Comment by Stephan202** [comment]
Seems the `CHANGELOG` hasn't been updated in quite some time. Are the release notes perhaps tracked elsewhere?

**Comment by cbeust** [comment]
Indeed, I haven't been as diligent asking people who send pull requests to
update it, and I usually update the documentation as soon as I merge. I
will need to go through the commit log and put this together.

-- 
Cédric

**Comment by simon04** [comment]
Done in #282.
