### ISSUE TITLE
Main argument with "-" prefix

### ISSUE THREAD

**Issue by gharlan** [cbeust/jcommander#170]
My main arguments are math. function terms. If a function starts with a minus, I get a `ParameterException: Unknown option`.

Example 1: `foo -a AAA -b BBB "2*x+1"` this works.

Example 2: `foo -a AAA -b BBB "-2*x+1"` this not. Result:

```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -2*x+1
    at com.beust.jcommander.JCommander.parseValues(JCommander.java:735)
    at com.beust.jcommander.JCommander.parse(JCommander.java:279)
    at com.beust.jcommander.JCommander.parse(JCommander.java:262)
```

**Comment by jahhulbert-ccri** [comment]
i vote for this one too...I also noticed that @madrob and a few others had a conversation on https://issues.cloudera.org/browse/KITE-854 for a similar feature...allowing a single dash "-" to read from std in. which is a syntax i like and just tried to use

**Comment by jeremysolarz** [comment]
@cbeust an old one but shall this be implemented?

**Comment by jeremysolarz** [comment]
Works in latest master

```
public void math() {
        class Args {
            @Parameter(names = "-a")
            public String a;

            @Parameter(names = "-b")
            public String b;

            @Parameter()
            public List<String> main;
        }

        JCommander jc = new JCommander();
        Args args = new Args();
        jc.addObject(args);

        jc.parse("-a", "AAA", "-b", "BBB", "-2*x+1");

        Assert.assertEquals("-2*x+1", args.main.get(0));
    }
```
