### ISSUE TITLE
jline shell for JCommander?

### ISSUE THREAD

**Issue by jstrachan** [cbeust/jcommander#18]
I really like the sub-command thing so you can build something like "git commands args".

It would be cute if we could create a "Shell" command so you could do the equivalent of "git shell" then be in a shell where you can execute sub-commands as top level commands with up/down/history and tab completion using something like...

http://jline.sourceforge.net/

either that or a plugin for bash completion for jcommander commands

**Comment by eolivelli** [comment]
I found this cool project
https://github.com/nikolavp/commander-shell
