### ISSUE TITLE
Converters for non-collection parameters with arity>1

### ISSUE THREAD

**Issue by eyalroth** [cbeust/jcommander#181]
I would really love to be able to write converters that accept a list of values (when my parameter uses arity>1), and then convert them into my custom object (not necessarily a collection).

Or in other words:

``` java
public class MyConverter implements IStringListConverter<MyObject> {
    public MyObject convert(List<String> values) {
        return ...;
    }
}

@Parameters
public class MyCommand {
    @Parameter(converter = MyConverter.class, arity = 2)
    private MyObject obj;
}
```

**Comment by jeremysolarz** [comment]
For future uses. This can indeed not be achieved the the current implementation of `JCommander` but as a workaround the converter can accept a String value and be provided with a list of strings separated via command line. e.g.

```
public class MyConverter implements IStringConverter<MyObject> {
    public MyObject convert(String values) {
        String [] items = commaSeparated.split(",");
        List<String> list = Arrays.asList(items);
        return new MyObject(list);
    }
}

@Parameters
public class MyCommand {
    @Parameter(names="-obj", converter = MyConverter.class)
    private MyObject obj;
}
```

and call it like

`java App -obj value1,value2
