### ISSUE TITLE
Require subcommand

### ISSUE THREAD

**Issue by rupert654** [cbeust/jcommander#186]
Currently, it doesn't appear possible to make selecting at least one subcommand, required.

``` java
public class ExampleCommand {
  @Parameter(names = "--id", required = true) private String id;
}

public class Main {
  public static void main(String[] args) {
    JCommander parser = new JCommander();
    parser.addCommand("example", new ExampleCommand());
    parser.parse(new String[] {});
  }
}
```

No ParseException is thrown. Is this behaviour expected? It seems counter-intuitive since if I pass in an non-existent command name then an error will be thrown but passing in no input, as above, results in nothing. I then have to check whether getParsedCommand returns null and throw a ParseException manually.

Is there some other way I can make selecting at least one subcommand required?

**Comment by jeremysolarz** [comment]
@cbeust what do you say, do you think this is in line with what `JCommander` should do?

**Comment by cbeust** [comment]
We could add a `required` boolean when adding the command but since this is pretty easy to enforce manually after JCommander has parsed the command line, not urgent.
