### ISSUE TITLE
Added command's JCommander not inheriting value set in setAcceptUnknownOptions()

### ISSUE THREAD

**Issue by efa85** [cbeust/jcommander#190]
When using normal(not commands) annotated object added to JCommander via constructor or addObject(), setAcceptUnknownOptions() works as expected and if an unknown parameter is passed the parsing just ignores it. 
The problem is that this is not true when you pass a command object(using addCommand()). addCommand creates a new JCommander and its acceptUnknownOptions is not inherited from the parent JCommander where we call addCommand. Therefore an exception is thrown if any unknown parameters is found for that command.

I think the expected behaviour should be that once you set acceptUnknownOptions it affects also the added commands, not only the objects.

**Comment by cbeust** [comment]
New version released on Dec 18th, 2014.
