### ISSUE TITLE
[FUNC. REQUEST] Allow parameters to be overrided by last occurence of such

### ISSUE THREAD

**Issue by Antoniossss** [cbeust/jcommander#192]
Can you tell me please, why JCommander does not allow paratemeters to override themselves? When single parameter occurs twice on command line, JCommander will throw an exception telling that such parameter can occur only once.

I am using workaround by creating private List<argument> insteed of private argument and pick up only last value via getters. Why it is not configurable (eg. via parameter in @Parameter annotation like `allowOverride=true` or something?

Why such request?
I have application with a lot of input parameters. It is lunched via BAT or SH script with some parameters as they are lunched automaticly by external lunchers. However sometimes (on production or developement for debuging/testing) I want to lunch such app with changed one or two parameters. I don't want to edit lunch script everytime. I would like to simply pass that argument to BAT or SH so it would be added to command in such script and override values from script itself.

**Comment by bacar** [comment]
+1. I have @args files which are essentially defaults (with different defaults for different environments) - but I want to be able to override the values from those arg files from the cmd line.

It would be nice to be able to opt-in to a "command line beats args-file" mode, or even a "last specified value wins" mode.

**Comment by TKlerx** [comment]
You can specify this with JCommander.setAllowParameterOverwriting
I think this is your "last specified value wins" mode.

**Comment by bacar** [comment]
Aha, I'll give that a go. Do you know which of cmd line vs @args wins if I set that?

**Comment by TKlerx** [comment]
No, I don't know but the @file-arg is a bit buggy when using the standard separator ' ' if I am correct. I already made a pull request on that but there was no comment on it.

**Comment by bacar** [comment]
It appears from the original PR that the intent of `setAllowParameterOverwriting` is precisely for command line args to beat file args, sweet.

https://github.com/cbeust/jcommander/pull/199#issuecomment-49745797

**Comment by Antoniossss** [comment]
But is it possible to override args only from command line? In my case, I am not using conf file, only lunch script, so I am appending to it with $*

**Comment by bacar** [comment]
Yes, it's just last wins.

**Comment by simon04** [comment]
@cbeust, @jeremysolarz: Nothing to be done; issue be closed.

**Comment by jeremysolarz** [comment]
@simon04 ok closing.
