### ISSUE TITLE
How to validate input parameters (string or value) against other parameters using JC validation mechanisms?

### ISSUE THREAD

**Issue by Antoniossss** [cbeust/jcommander#193]
For example lets say that I have 2 optional date parameters `-from` and `-to` 
Now I need to validate if `-from` is not after `-to` end vice versa. 
I am doing it right now after parameters parsing. Is there any way to do this using validation mechanism used by JCommander without writing internal classes? Maybe `ParametersAwareValidator` interface would be nice feature.

**Comment by jeremysolarz** [comment]
Hi @Antoniossss,

This sounds like a rather special feature, but let's see what @cbeust says. 😄

**Comment by cbeust** [comment]
Just validate it yourself after the parsing.
