### ISSUE TITLE
Comma in the arguments

### ISSUE THREAD

**Issue by valtih1978** [cbeust/jcommander#194]
I declared argument

```
@Parameter(names = "-s", description = "python script to execute", variableArity = true)
private List<String> fScript = new ArrayList<>();
```

used as

```
for (String script : fScript) {
    System.out.println("evaluating script = " + script);
    pyEngine.eval(script);
}
```

in order to support MyProgram -s "script1" -s "script2"

MyProgram -s "print 'a' + 'b'" is parsed properly. However, 
MyProgram -s "x,y = 1,2" says evaluating script = x and "x" is undefined. 

Do you see that I pass "x,y = 1,2" instead of "x"? How does your library say that I pass "x"? What should I do with your library?

**Comment by jeremysolarz** [comment]
Dear @valtih1978,

I know this is an old question but nevertheless.

JCommander splits by default strings in `List` by commas. What you could do in this case is the following:

```
public class VariableArity {

    @Parameter(names = "-s", description = "python script to execute", splitter = NoSplitter.class)
    private List<String> fScript = new ArrayList<>();

    @Test
    public void test(){
        JCommander jc = new JCommander(this);
        jc.parse("-s", "x,y = 1,2");
        for (String script : fScript) {
            System.out.println("evaluating script = " + script);
        }
    }

    public static class NoSplitter implements IParameterSplitter {
        @Override
        public List<String> split(String value) {
            return Arrays.asList(value);
        }
    }
}
```

**Comment by PureCS** [comment]
Note: Commas may also be missing if you are reading input from the command-line arguments in Powershell.  
See: https://stackoverflow.com/a/24784272
