### ISSUE TITLE
Don't prompt for password if it was passed as argument

### ISSUE THREAD

**Issue by bramp** [cbeust/jcommander#195]
This is a feature request.  I would like to accept a password as a argument, or if it's missing prompt for it. This would work in a similar way to "mysql -p", for example:

```
$ mysql -p
Enter password: 
...
```

or

```
$ mysql -pSomething
...
```

**Comment by jeremysolarz** [comment]
@cbeust hm the request is valid

A call like this
```
public class Password {
    public static class ArgsPassword {
        @Parameter(names = "-password", description = "Connection password", password = true)
        private String password;
    }

    public static void main(String[] args) {
        ArgsPassword arg = new ArgsPassword();
        JCommander jc = new JCommander(arg);
        jc.parse("-password", "test");
    }
}
```
still asks for the password.

**Comment by cbeust** [comment]
Agreed.

**Comment by triceo** [comment]
@jeremysolarz This issue is assigned to you - are you working on it? If not, I may take a stab at it.

**Comment by jeremysolarz** [comment]
Yes, please! 😄

**Comment by triceo** [comment]
@jeremysolarz PR submitted. Feel free to review or let me know if I should ask someone else.
