### ISSUE TITLE
Optionally allow duplicates

### ISSUE THREAD

**Issue by haridsv** [cbeust/jcommander#197]
When scripting, it is very convenient to override default parameters by appending the parameters at the end. E.g., let us say `DEFAULT_OPTS=-t 10` and this is being used as `prog.sh $DEFAULT_OPTS`, it would be very convenient to override the default for `-t` by specifying the new value at the end, e.g., `prog.sh $DEFAULT_OPTS -t 20`. Currently, repetition of options is treated as an error, when the Java type is not a List. For non-List types, this should by default accept the last value or at least have an option via Parameter annotation, that indicates that this is acceptable.

**Comment by jeremysolarz** [comment]
@haridsv Hi Hari,
I guess this is a rather special request that would not make sense for a lot of users.

@cbeust what do you say?

**Comment by cbeust** [comment]
Agreed.
