### ISSUE TITLE
for help related sub-commands being able to inject the JCommander as a @Parameter (or maybe a different annotation) would be handy

### ISSUE THREAD

**Issue by jstrachan** [cbeust/jcommander#20]
I'm finding I have to treat help related commands which need to invoke JCommander.usage differently to other commands when doing git style multi-command things.

It would make code simpler if we could inject the JCommander object into the command.

**Comment by jeremysolarz** [comment]
@cbeust closing since no answer since 6 years.

**Comment by cbeust** [comment]
Six years?!?

Makes me feel so old 😢

**Comment by jeremysolarz** [comment]
😅
