### ISSUE TITLE
Incorrect usage() formatting with single long options

### ISSUE THREAD

**Issue by jikuja** [cbeust/jcommander#200]
jcommander 1.30: usage() indents single long options incorrectly
```
java -jar build/libs/FTB_Launcher-1.4.4-9999999.jar
Usage: Feed The Beast Launcher: 1.4.4 [options]
  Options:
        --cache-dir
       Cache directory
        --dynamic-dir
       Dynamic directory
        --help

       Default: false
    -V
       Level of verbosity

```

Root cause of the problem: https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/ParameterDescription.java#L189 which is adding spaces

If I add second name for argument then indentation is done correctly:
```
Usage: Feed The Beast Launcher: 1.4.4 [options]
  Options:
    --cache-dir, -C
       Cache directory
        --dynamic-dir
       Dynamic directory
        --help

       Default: false
    -V
       Level of verbosity
```

**Comment by tfiskgul** [comment]
This issue seems to be solved in https://github.com/cbeust/jcommander/pull/205 and should be closed?

**Comment by boillodmanuel** [comment]
Agree
