### ISSUE TITLE
helper facade for sub commands? 

### ISSUE THREAD

**Issue by jstrachan** [cbeust/jcommander#21]
I found there was a bit of head scratching & glue code work to figure out how to make a 'git' like set of commands needing the following...
- making a Map name -> command 
- add the contents of the map to the JCommander
- creating a new Help command so that you could  type "help" to list all the commands or "help foo" to show help on a sub command (right now the help command needs a reference to JCommander)
- doing the try/catch around the parse/run, printing out the usage on failures
- when parsing works, looking up the parsed command in the Map then executing it

I wonder if its worth a little helper class for wrapping up this code so others can reuse it - as none of it really is application specific.

e.g. a facade object which can be configured with the Map<String,Object> commands, adds a Help command by default if there's none already provided that does the common thing and has a few strategy methods that folks could override if required (say to print something before/after an error) that does the try/catch stuff and looks up the command to execute and then invokes the command - by default testing if its a Runnable and calling run() otherwise failing?

It would be nice to be able to do code something like...

```
Map<String,Runnable> myCommands = new ....
JCommanderRunner runner = new JCommanderRunner(myMainThingy);
runner.setCommands(myCommands);
runner.run(args);
```

And if a command is a Runnable it'd just do the right thing without any code required. If you're commands are not runnable then you could derive from JCommanderRunner and override the execute(Object command) method to do something application specific (but Runnable seems a reasonable default for now).

**Comment by jeremysolarz** [comment]
Hi @jstrachan,

Can you please elaborate on your example. 

Best,

JS

**Comment by jeremysolarz** [comment]
Closing since no response.
