### ISSUE TITLE
Formatting of usage is broken for parameters with multiple names and a default

### ISSUE THREAD

**Issue by silasdavis** [cbeust/jcommander#214]
If I have a Command class like:

``` Java
@Parameters(commandDescription = "Infer missing metadata")
public class MetadataInferenceCommand extends CommandBase {
  @Parameter(names = "--to",
             description = "Process data logged before this date, yyyyMMdd",
             converter = YYYYMMDDDateConverter.class)
  public Date toDate = new Date();

  @Parameter(names = {"--input", "-i"},
             description = "Path or URL for input",
             required = true)
  public String inputPath;

  @Parameter(names = {"--output", "-o"},
             description = "Path or URL for output",
             required = true)
  public String outputPath;
}
```

where I have used a mixture of parameters with multiple names and parameters with single names. The formatting of the usage for the command is broken. 

Specifically the parameters with just a single name align with the description of preceding multiply-named parameter rather than with the parameter flag. This hides the singly-named parameters and makes the usage hard to read:

```
Infer missing metadata 
Usage: MetadataInference(mi) [options]
  Options:
  * --input, -i
       Path or URL for input
  * --output, -o
       Path or URL for output
        --to
       Process data logged before this date, yyyyMMdd
       Default: Fri Feb 13 18:36:55 UTC 2015
    -help, -h

       Default: false
```

Notice the `--to` parameter description in the above.

I'm using JCommander 1.47

**Comment by jeremysolarz** [comment]
@silasdavis this should be fixed in the latest version from the repo. Please test.

**Comment by jeremysolarz** [comment]
@cbeust I guess this can be closed. Tested and works in latest version.
