### ISSUE TITLE
IValueValidator for lists (arity > 1)

### ISSUE THREAD

**Issue by gehel** [cbeust/jcommander#215]
It seems at the moment that for parameters with arity > 1 (lists) validators are called with the list passed as the value. This make sense in the general case where we want to validate the full content of the list. Another use case is that we want each element of that list to have the same constraints. In my case, I have a parameter "--configFiles" on which I want to apply an `ExistingFileValidator` that ensure that each file exists.

Of course, I can write an `ExistingFileCollectionValidator`, but there should be an easier way to apply the same validator on all elements of a list.

**Comment by jeremysolarz** [comment]
@gehel in the latest version of JCommander this is fixed.

Please see the following test case

```
public class ValidatorTest {

    public static class PositiveInteger implements IParameterValidator {
        public void validate(String name, String value)
                throws ParameterException {
            int n = Integer.parseInt(value);
            if (n < 0) {
                throw new ParameterException("Parameter " + name + " should be positive (found " + value +")");
            }
        }
    }

    @Parameter(names = "-ages", arity = 2, validateWith = PositiveInteger.class)
    private List<Integer> ages;

    @Test
    public void test(){
        JCommander jc = new JCommander(this);
        jc.parse("-ages", "20", "30");
    }
}
```

**Comment by gehel** [comment]
Time for me to upgrade! Thanks!
