### ISSUE TITLE
Support Map parameters

### ISSUE THREAD

**Issue by WACMemphis** [cbeust/jcommander#218]
It would be nice if jcommander could support `Map` parameters.

Something like `Map<String, MyObject>` ideally. I have an `IStringConverter` that generates `MyObject` from a `String`.

The user could then provide them using `-m firstString firstObject -m secondString secondObject`.

**Comment by cbeust** [comment]
They would have to be all of the same type, and then I don't see how this is different from a `List` of these objects...

**Comment by WACMemphis** [comment]
Well, the first parameter is always of the same type and the second parameter as well, but the first and second may be of a different type.

Not sure how I'd be able to use a `List` here, as I'm dealing with two different objects here.

**Comment by cbeust** [comment]
Sorry I don't understand what you mean... The first and second are of the
same type but they are not?


-- 
Cédric

**Comment by WACMemphis** [comment]
Sorry, let me try to explain:

Let's assume I want to have something like this (no valid Java):

Syntax: `{key: value}`
`[{"first": myObject1}, {"second": myObject2}]`

Which would end up in a `Map` defines as follows: `Map<String, MyObject>`

So, there are two data types, `String` and `MyObject`.

It would be nice if there was a feature that allows me to do:

    @Parameter(names = "-m", valueConverter = MyObjectConverter.class)
    private Map<String, MyObject>

Optionally there could be a `keyConverter` as well, but as it's a `String`, this wouldn't be necessary in this example.

The user could then provide the parameters as:

`-m first somethingToConvertToMyObject1 -m second somethingToConvertToMyObject2`

I hope this makes sense to you now.

**Comment by cbeust** [comment]
Yes, I understand. Right now, you could emulate this by using a list,
though:

-m first:object1 second:object2

Then you create your map by splitting keys and values around the :...

-- 
Cédric

**Comment by WACMemphis** [comment]
How?

**Comment by cbeust** [comment]
Make your parameter field a List<String>...

-- 
Cédric

**Comment by WACMemphis** [comment]
Well, then I end up with a `List` of `String`s instead of the mapping I would need.

I can work my way around this, I know. I just thought it would be a nice feature.

**Comment by jeremysolarz** [comment]
Dear @WACMemphis, 

An implementation would be something along this lines

**Class for object with key and SubObject**
```
public class MyObject {
    String key;
    SubObject value;

    public static class SubObject {
        public String attr1;
        public String attr2;

        public SubObject(String attr1, String attr2) {
            this.attr1 = attr1;
            this.attr2 = attr2;
        }
    }

    public MyObject(String key, SubObject value) {
        this.key = key;
        this.value = value;
    }
}
```

**Converter to convert values like key1:{attr1:val1.1, attr2:val1.2}**
```
import com.beust.jcommander.IStringConverter;

public class MyObjectConverter implements IStringConverter<MyObject> {
    @Override
    public MyObject convert(String value) {
        String[] parts = value.split(":", 2);
        String key = parts[0];
        String subObject = parts[1];

        subObject = subObject.replaceAll("[{}]", "");
        // attr1:val1.1, attr2:val1.2
        parts = subObject.split("[,:]");

        return new MyObject(key, new MyObject.SubObject(parts[1].trim(), parts[3].trim()));
    }
}
```

and here the 

**TestCase**
```
import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.util.List;

public class MyObjectList {


    @Parameter(names="--objects", variableArity = true, listConverter = MyObjectConverter.class)
    List<MyObject> objects;

    @Test
    public void testMain() {
        JCommander jc = new JCommander(this);
        jc.parse("--objects", "key1:{attr1:val1.1, attr2:val1.2}", "key2::{attr1:val2.1, attr2:val2.2}");
        Assert.assertNotNull(objects);
        Assert.assertEquals(2, objects.size());
        Assert.assertEquals("key1", objects.get(0).key);
        Assert.assertEquals("val1.1", objects.get(0).value.attr1);
    }
}
```

**Comment by jeremysolarz** [comment]
@cbeust guess we can close it since work-around is possible
