### ISSUE TITLE
20 tests fail in JCommanderTest

### ISSUE THREAD

**Issue by TKlerx** [cbeust/jcommander#220]
If you run JCommanderTest.java 20 tests fail and 63 pass.

**Comment by cbeust** [comment]
I just pulled and everything looks fine to me:

```
$  java -classpath "target/classes;target/test-classes;../testng/target/testng-6.8.20.jar;" org.testng.TestNG src/test/resour
ces/testng.xml
[TestNG] Running:
  C:\Users\cbeust\java\jcommander\src\test\resources\testng.xml


===============================================
JCommander
Total tests run: 153, Failures: 0, Skips: 0
===============================================
```

**Comment by TKlerx** [comment]
So is there a difference when run from eclipse?
I get the following output: [TestNG] Running:

[...]\git\jcommander\src\test\resources\testng.xml

===============================================
JCommander
Total tests run: 153, Failures: 38, Skips: 0
===============================================
