### ISSUE TITLE
can we add a switch in usage() to not print sub-command options

### ISSUE THREAD

**Issue by hotterd** [cbeust/jcommander#224]
Currently when I call jc.usage() on a JCommander instance that has several sub-command configured, it prints all description of main program as well as all description of sub-command options. This can be what we want. But sometimes, when the sub-command list is long, we probably do not want to show every option of the sub-command, it might generate a very long and overwhelming usage message.

What I'm proposing is to add a switch that can control JCommander to not go into deepest level of description, but just prints the main options description followed by command description. Something like below:

Usage: MyApp [options] [command] [command options]
  Options:
    -d, -debug
       debug mode
       Default: false
    -h, -help
       print this message
       Default: false
    -q, -quiet
       be extra quiet
       Default: false
    -v, -verbose
       be extra verbose
       Default: false
  Commands:
    command1      a command description
    command2      another command description
    command3      more
    ....

If user want to see the detailed options for each sub-command, they can type "MyApp command1 -help" to call the command usage. This will keep the main usage from printing too long and making user losing the focus.

Thanks,
Gan Dong

**Comment by andrewbaxter** [comment]
I'd also like the option to be able to print just a single sub-command's usage, like `jc.usage("command1")` or something.  Sorry if this decreases the focus of the issue, it seems like a logical complement though.

I also have a dozen or so commands, each with 5-6 parameters.

**Comment by jeremysolarz** [comment]
@cbeust what do you say? Necessary?

**Comment by cbeust** [comment]
Probably not. My general approach to `usage()` is to not spend too much time on it (since there are so many opinions from users on what it should look like) and let people who want a different format write their own.

**Comment by jeremysolarz** [comment]
@cbeust ok I guess we can close it then?
