### ISSUE TITLE
Call usage despite of missing required parameter.

### ISSUE THREAD

**Issue by hansgru** [cbeust/jcommander#225]
Hi,

especially when the user forgets one of the missing parameters, I would like to display the `jcommander.usage()` function too after the `e.getLocalizedMessage()`, but this does not seem possible since the JCommander instance is not complete so it gives an NPE.

**Comment by jeremysolarz** [comment]
@hansgru this should work with the latest version.

At least this code works (if that is what you meant)

```
public class Foo {
    @Parameter(names={"-bar", "--bar"})
    private int bar;

    @Test
    public void testMain() {
        JCommander jc = new JCommander(this);
        try {
            jc.parse("");
        } catch(ParameterException pe){
            System.out.println(pe.getLocalizedMessage());
            jc.usage();
        }
    }
}
```

**Comment by jeremysolarz** [comment]
@cbeust I guess this can be closed. :)
