### ISSUE TITLE
List parameter and main parameter conflict

### ISSUE THREAD

**Issue by KaiPierre** [cbeust/jcommander#238]
I have an issue trying to run a command with a multiple values parameter : 

```shell
command mainParam --list arg1,arg2,arg3 #OK
command --list arg1,arg2,arg3 mainParam  #KO
```
Option are setted llike : 
```java
@Parameter(required = true, description = "Main param")
	private List<String> mainParameter;
@Parameter(names = "--list", variableArity = true, description = "A list")
	private final List<String> list = new ArrayList<String>(); //Use the default CommaParameterSplitter splitter
```
and error return is simply : 
`Error: Main parameters are required ("Main param")`

This is a library limitation ? And issue or an error in my code ?

Edit : KO version work if parameter is a String or a Boolean for example

**Comment by cbeust** [comment]
This is working as intended.

You declared your `--list` parameter as `variableArity`, which means that JCommander will consume all the parameters that follow it until it encounters the next option (or the end). In this case, it causes you `mainParam` to be parsed as part of the list and when comes the time to find a main parameters (which you declared `required`), there is no more parameter left to parse.
