### ISSUE TITLE
Parameter validation with multiple parameter names

### ISSUE THREAD

**Issue by brvieitas** [cbeust/jcommander#242]
When a validation class associated to a parameter is called, either using **validateWith** or **validateValueWith**, the name of the argument passed to the validator is not the same given by the user in the command line.

Parameters class:

``` java
@Parameters(commandDescription = "Configure database access")
public class DatabaseArguments {

    @Parameter(names = { "-i", "-h" }, description = "Ip address or Hostname", validateValueWith = IPAddressValidator.class, required = true)
    private String ipHost;

}
```

Validator class:

``` java
public class IPAddressValidator implements IValueValidator<String> {

    public void validate(String name, String value) throws ParameterException {
        if (name.equals("-i")) {
            // Doing some validations here
         }
     }
}
```

For the given example, there is two possible parameters (-i or -h) that will associate the value to the same variable. When validating, the method **validate** should receive the chosen option, however it is always receiving the first option configured in the Parameter annotation.

For aditional information, I'm currently using jcommander version 1.48.
When looking at the code, I found that the class **ParameterDescription** has the following line of code in **addValue** method:

``` java
String name = m_wrappedParameter.names()[0];
```

This variable is then given to the validation class. This statement always picks the first option in a list of possible options, however it should choose the one that was given as argument.

Thanks!

**Comment by jeremysolarz** [comment]
@cbeust I think this is solved with the PR for issue 309 :smile:
