### ISSUE TITLE
Blank lines added for parameters with missing descriptions

### ISSUE THREAD

**Issue by andrewbaxter** [cbeust/jcommander#246]
This makes it fairly difficult to read the usage output.

Example:

```
       Default: -1
    --help, -h

       Default: false
    --isOn
```

**Comment by jeremysolarz** [comment]
@cbeust shall this be changed?

**Comment by cbeust** [comment]
Pretty sure there will be as many people liking this change as people complaining about it (because it makes your screen scroll), so closing.
