### ISSUE TITLE
Add getter for program name

### ISSUE THREAD

**Issue by btiernay** [cbeust/jcommander#247]
Useful for passing `JCommander` between objects and accessing the previously set program name.

**Comment by JesusFreke** [comment]
+1. I needed this to be able to do my own usage formatting. Also, the ability to look up a subcommand by alias, which is useful for something like a "help" command, to show the (custom formatted) usage info for other commands. e.g. <program> help <command>

**Comment by jeremysolarz** [comment]
@cbeust shall this be implemented?

**Comment by cbeust** [comment]
@jeremysolarz No objection if you want to do it and send a PR.

**Comment by jeremysolarz** [comment]
@btiernay, @JesusFreke, @ccamel what exactly are you considering as "program name"?

**Comment by ccamel** [comment]
@jeremysolarz by "program name", I mean the private field named `m_programName` in the `JCommander` class. You already have setters (`setProgramName`) for this field, but no getters.

**Comment by jeremysolarz** [comment]
@ccamel thanks for clarifying. Will be implemented 😄

**Comment by jeremysolarz** [comment]
Closing. Feature is implemented in latest master.
