### ISSUE TITLE
Allow enum converters to be picked up by a custom IStringConverterFactory

### ISSUE THREAD

**Issue by btiernay** [cbeust/jcommander#248]
Currently this is not possible due to the way `JCommander#convertValue` works. See https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L1253

**Comment by btiernay** [comment]
Actually, this may have been fixed in a more recent version, but not released. If so, please close.

**Comment by btiernay** [comment]
It was committed  committed but not in 1.48

**Comment by simon04** [comment]
The change you are referring to is 136d6ec2b7508220514146ad7f787c24977cb632 and has been merged in #179 on 18 May 2015. Version 1.48 has been released on 11 Apr 2015.

IMO, this issue can be closed.
