### ISSUE TITLE
"Required unless" arguments

### ISSUE THREAD

**Issue by ryonday** [cbeust/jcommander#249]
I haven't found a way to cleanly implement the useful concepts of "at least one of these options is required" or "At least one, but not both"  within JCommander; although it's certainly possible to check this after the parsing step, it would be cool to not have to rely on this kind of post-processing.. 

For instanc

**Comment by cbeust** [comment]
JCommander's philosophy is to leave this kind of complex validation up to the developer. It's just much easier to write a few lines of code than coming up with a declarative way to enforce complex validation rules.

**Comment by jeremysolarz** [comment]
@cbeust shall this be closed?
