### ISSUE TITLE
help command does not support multiple option names

### ISSUE THREAD

**Issue by anthraxn8b** [cbeust/jcommander#250]
The example for the help option on http://jcommander.org/ works:
```java
@Parameter(names = "--help", help = true)
private boolean help;
```
Using multiple option names does not work
```java
@Parameter(names = { "-h", "--help" }, help = true)
private boolean help;
```

**Comment by acostalima** [comment]
You did not specify help = true. See below.

@Parameter(names = { "-h", "--help" }, help = true)
private boolean help;

**Comment by anthraxn8b** [comment]
I did :-)
THX!

**Comment by anthraxn8b** [comment]
However. Whatever I did wrong... Now it works.
