### ISSUE TITLE
If you define a list as argument to be parsed with an IStringConverter, JCommander will create a list instead of a list.

### ISSUE THREAD

**Issue by krishnanand** [cbeust/jcommander#253]
I am trying to parse the spreadsheet with Apache POI to read the contents of each Excel spreadsheet. My implementation takes the resource path and builds list of objects.  I have found that if I have my IStringConverter return a list of objects, and I have configured my value object as a list of objects, JCommander builds a list of lists instead.

My reduced test case is as follows:

```
@Parameters(separators="=")
 class ParsedArguments {
   @Parameter(names="-resourcesToBeComparedAgainst",
           converter=ExcelSpreadSheetConverter.class)
   private List<Foo> resourcesToBeComparedAgainst;

       // Getters and setters.
}
```

My IStringConverter implementation is as follows: 

```
public class ExcelSpreadSheetConverter implements
    IStringConverter<List<Foo>> {

    @Override
    public List<Foo> convert(String resourcePath) {
          List<Foo> l = new ArrayList<>();
               l.add(new Foo());
           return Collections.unmodifiableList(l);  
   }
}
```

where Foo is a no arg, no op class.

When I invoke JCommander as follows

```
String[] argv = new String[]  {"-resourcesToBeCompared=foo"};
ParsedArguments pa = new ParsedArguments();
new JCommander(pa).parse(argv);
```

The value of ParsedArguments#resourcesToBeComparedAgainst is a list of lists.

While debugging the issue, I may have found the possible cause of an issue in JCommander#convertToList function

```
  /**
   * Use the splitter to split the value into multiple values and then convert
   * each of them individually.
   */
  private Object convertToList(String value, IStringConverter<?> converter,
       Class<? extends IParameterSplitter> splitterClass)
       throws InstantiationException, IllegalAccessException, NoSuchMethodException,
          InvocationTargetException {
    Constructor<? extends IParameterSplitter> constructor = splitterClass.getConstructor(new Class[0]);
    constructor.setAccessible(true);
    IParameterSplitter splitter = constructor.newInstance();
    List<Object> result = Lists.newArrayList();
    for (String param : splitter.split(value)) {
        result.add(converter.convert(param));
    }
    return result;
}
```

The code

```
    result.add(converter.convert(param));
```

adds the output of the converter to another list. This behaviour is probably correct, but does not work if a list is returned from an implementation of IStringConverter. One way to prevent this from happening could be to check if the converter output is a collection. If yes, then use **addAll** function instead of **add**. We can do that using _isAssignableFrom(Class<?>.class)_ function

If I have proposed the corrected approach, I can create a pull request and send it for review. If not, a better way to solve this issue would be appreciated. I need to create a list because there might be duplicate entries in the collection, so a Set will not work.

Any suggestion would be gratefully appreciated.

**Comment by klauern** [comment]
I just found this issue, too.  I had to do something weird in that I ended up putting a `List<List<type>> thing` instead, and just hard-coded a `.get(0)`.  It's ugly, though:

```java
    @Parameter(names = {"-env"}, converter = CommaSplitter.class, description = "Comma-separated list of environments to parse")
    private List<List<String>> environments = Lists.newArrayList();
...
     List<String> envs = environments.get(0);
        for (String env : envs) { ... }
```

and my converter is pretty simple:

```java
public class CommaSplitter implements IStringConverter<List<String>> {

    private Splitter commaSeparated = Splitter.onPattern(", ?").omitEmptyStrings().trimResults();

    @Override
    public List<String> convert(String value) {
        logger.info("Value is " + value);
        return commaSeparated.splitToList(value);
    }
}
```

**Comment by klauern** [comment]
In addition to this, the line that @krishnanand is mentioning is here:

https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L1356

**Comment by simon04** [comment]
You seem to be looking for `listConverter`, try:

```java
@Parameter(names = "-resourcesToBeComparedAgainst", converter = StringConverter.class, listConverter = ExcelSpreadSheetConverter.class)
```

… and see the example https://github.com/cbeust/jcommander/blob/master/src/test/java/com/beust/jcommander/args/ArgsList.java

**Comment by jeremysolarz** [comment]
@simon04 isn't it the `splitter` attribute they are searching for?
Nevertheless a bit odd that it's not mentioned in the documentation.

**Comment by jeremysolarz** [comment]
@cbeust shall I add splitter / listConverter to the documentation?

**Comment by cbeust** [comment]
@jeremysolarz Sure!

**Comment by jeremysolarz** [comment]
@cbeust done. Hope that the wording is ok. I guess this is not so easy to the right since everybody has his own style :smile:
