### ISSUE TITLE
Re-use of parameter delegates with differing prefixes

### ISSUE THREAD

**Issue by a2geek** [cbeust/jcommander#259]
Is there a mechanism to allow delegate to add a prefix to command options in the delegate?  I've been working on a project that accepts multiple database connection definitions.  Every single one is a JDBC URL, user name, password. It would be nice to define a meta-object and then re-use it.

Something like:

``` java
    public class Info {
        @Parameter(names = "--url", description = "JDBC URL")
        public String url;
        @Parameter(names = "--user", description = "Database user")
        public String user;
        @Parameter(names = "--password", description = "Database password", password = true)
        public String password;
    }
```

And then using and re-using it as:

``` java
    @ParametersDelegate(prefix = "db1")
    private Info db1info;
    @ParametersDelegate(prefix = "db2")
    private Info db2info;
```

The command-line would then be something like:

``` shell
myproject.sh --db1-url xyz --db1-user userxyz --db1-password \
             --db2-url abc --db2-user userabc --db2-password
```

 Thanks!

**Comment by cbeust** [comment]
No such a thing at this time.

**Comment by a2geek** [comment]
Then let's consider it a feature request. ;-)

**Comment by cbeust** [comment]
Consider it considered ;-)

-- 
Cédric
