### ISSUE TITLE
setCaseSensitiveOptions(boolean) does not work when using subcommands

### ISSUE THREAD

**Issue by tmescic** [cbeust/jcommander#261]
I am trying to make options of my CLI case insensitive. I am using setCaseSensitiveOptions(false) on my CLI that has several subcommands (added using JCommander.addCommand()). However, I am getting an error when I use different case.

This works fine:
java MyProgram subcommand --option ....

This does not work (I get an error: Unknown option: --oPTion):
java MyProgram subcommand --oPTion ....

**Comment by cbeust** [comment]
Fixed by https://github.com/cbeust/jcommander/pull/280.
