### ISSUE TITLE
IStringConverter does not allow using non-static nested classes

### ISSUE THREAD

**Issue by datasedai** [cbeust/jcommander#262]
JCommander does not allow using nested, non-static classes.  Specifically this code in instantiateConverter:

```
} else if (types.length == 0) {
        ctor = c;
      }
```

Embedded classes must have a hidden parameter to pass the instance of the class it's embedded in.

Look at the answer [here](http://stackoverflow.com/questions/17485297/how-to-instantiate-inner-class-with-reflection-in-java).

Since Parameterized was created from an instance of an object, I think it should be easy to pass the object instance to the constructor.

**Comment by simon04** [comment]
It would be "easy", if JCommander was aware of the parent's class type + reference (which it is not and cannot be). For a much simpler approach see #196/#279.

**Comment by jeremysolarz** [comment]
@datasedai does the solution provided by @simon04 solve your problem?

**Comment by jeremysolarz** [comment]
@cbeust can this be closed? No response since a long time...

**Comment by simon04** [comment]
I _cannot_ be fixed directly as shortly outlined in https://github.com/cbeust/jcommander/issues/262#issuecomment-244197045.

**Comment by jeremysolarz** [comment]
@simon04 I know. But the user didn't response and you provided a workaround. So the question was if we can close it then. You think we should leave it open?
