### ISSUE TITLE
Jcommander 1.48 NPE in Jcommander.usage line 1134

### ISSUE THREAD

**Issue by GorillaCoder** [cbeust/jcommander#270]
Code does: 

Parameters p = arg.getClass().getAnnotation(Parameters.class);
if (!p.hidden()) {

But, if the command class is not marked with @Parameters, NPE. Should probably be `if (null!=p&&!p.hidden()) {`

**Comment by jeremysolarz** [comment]
Fixed in latest _master_ see https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L1146

**Comment by jeremysolarz** [comment]
@cbeust any update?

**Comment by cbeust** [comment]
I just deployed 1.60 to JCenter:

http://jcenter.bintray.com/com/beust/jcommander/1.60/
