### ISSUE TITLE
Reusing JCommander object fails

### ISSUE THREAD

**Issue by Agadar** [cbeust/jcommander#271]
I'm trying to reuse a JCommander instance, because I'm trying to create a simple Command Prompt-like Java front-end. I instantiate it and add a test command as such:

```
JCommander jc = new JCommander();
JCommanderTest jct = new JCommanderTest();
jc.addCommand(jct);
```

I then attempt to parse the command twice, as such:

```
String[] argv = {"example", "-log", "2", "-groups", "unit"};
parseAndExecute(argv);

String[] argv2 = {example", "-log", "3", "-groups", "unit2", "unit3"};
parseAndExecute(argv2);
```

Where parseAndExecute is defined as such:

```
private void parseAndExecute(String[] args)
    {
        jc.parse(args);
        String parsedCommand = jc.getParsedCommand();
        JCommander parsedJCommander = jc.getCommands().get(parsedCommand);
        IJCommand commandObject = (IJCommand) parsedJCommander.getObjects().get(0);
        commandObject.execute();        
    }
```

IJCommand is an interface that defines only the single method execute().

Now, the first time an array is parsed, it works as expected. However, the second time it gives the following exception:

> Exception in thread "main" com.beust.jcommander.ParameterException: Can only specify option -log once

Does this mean it is not possible to reuse a JCommander object in this fashion? And if it is not possible, then what workaround is recommended?

**Comment by acostalima** [comment]
You can always (re)create a new JCommand instance as a workaround.

**Comment by Agadar** [comment]
That works, certainly. But surely I shouldn't have to. Or am I misinterpreting the purpose of this library?

**Comment by acostalima** [comment]
I'm not really sure what @cbeust has in mind, but the way it works seems that you just run your program with the command line params, call JCommander to parse them, do what you have to do and terminate the program. AFAIK, it does not seem to be designed to implement an interactive prompt.
I've ran into this issue in the past and I just did what I suggested as a workaround.

**Comment by jgangemi** [comment]
same here - i use `jcommander` as a parser for a chat bot that uses a command style syntax and i had to re-create the object each time.

**Comment by Agadar** [comment]
I started working on something of my own to implement the behavior I desired of JCommander, but which it does not support (re-usability of JCommander instance such as in command-line applications or chat applications). The project can be found [here](https://github.com/Agadar/JavaCommander).

**Comment by acostalima** [comment]
@Agadar I wonder why you didn't fork JComander instead to implement the functionality you desire.

**Comment by Agadar** [comment]
@acostalima Felt like getting acquainted with Java annotations first, and making something myself from scratch before daring to do something like forking JCommander. Might still do so in the future, though.

**Comment by jgangemi** [comment]
ugh - why fork the project instead of just submitting a pull request?

**Comment by cbeust** [comment]
You need to fork before you can submit a pull request.

-- 
Cédric

**Comment by jgangemi** [comment]
yes of course you do. sorry - i took forking to mean something different in this context.
