### ISSUE TITLE
Simple global validation if annotated properly or implements PostBindValidation alike interface 

### ISSUE THREAD

**Issue by Antoniossss** [cbeust/jcommander#277]
Hey.
Just a suggestion. In general i agree with 4.2 - Global parameter validation from the manual, that some complex validation can be tricky to do in declarative way. But IMHO JCommader could at least support simple post binding validation in case if eg.

 @Parameters(postValidationClass=ValidatorClass.class) or 
 @Parameters annotated class implements some interface eg IPostValidation; 

the same would be done to @ParametersDeleage.

JCommander has to analyze all the annotations and stuff anyway, so why not enqueue such detected objects while doing so, and invoke some sort of validation method after normal parsing and binding process? (interface would be great for that I guess).

This will not cover some very complex validation (eg. checking if hostnames are valid and accessible, is remote configuration valid etc. etc.) but would cover most cases like: Dates ranges - FROM cannot be after TO, if one param is specified, then second one is not allowed.

Such logic feels natural to be placed along with the parameters definition.
This is just a suggestion.

Dont know JCommander internals, but should be rather easy to implement. 

Cheers!

BTW. Still using JCommander after 3 years :) Good job and keep it up.

**Comment by jeremysolarz** [comment]
@cbeust any statement to this PR?

**Comment by cbeust** [comment]
It's pretty simple to validate manually right now (just call validate on the objects yourself), so I don't think that JCommander doing this for you would be very helpful.
