### ISSUE TITLE
JCommander.addConverterFactory is not threadsafe

### ISSUE THREAD

**Issue by DavidZemon** [cbeust/jcommander#278]
Make `JCommander.addConverterFactory()` a static method since it is only modifying a static variable. I'm hitting a `java.util.ConcurrentModificationException` because I did not realize this method wasn't threadsafe.

**Comment by simon04** [comment]
@cbeust: Having #280 merged, we could add the list of factories to the `Option` class. Moving from `LinkedList` to `CopyOnWriteArrayList` would add thread safety. What do you think?
