### ISSUE TITLE
Version 1.57 vs. 1.58?

### ISSUE THREAD

**Issue by simon04** [cbeust/jcommander#297]
In Git we have a [1.57 branch](https://github.com/cbeust/jcommander/releases/tag/1.57), whereas [on Maven](https://repo1.maven.org/maven2/com/beust/jcommander/) there's only a 1.58 version. Are they the same? Or is just the Git tag for 1.58 missing?

**Comment by ehein6** [comment]
Looks like they have the same commit hash, so they must be the same: https://github.com/cbeust/jcommander/commit/3f95e02af31f8cc167b9b33888ea4fb4132b8282

**Comment by jeremysolarz** [comment]
@simon04 can this issue be closed?

**Comment by garydgregory** [comment]
Does 1.57 require Java 7 or 8?
Does 1.58 require Java 7 or 8?

**Comment by jeremysolarz** [comment]
@garydgregory Since they both point to they same commit hash it looks like they are the same.
If you checkout the tag the pom has 1.7 both as source and as target
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.1</version>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
```
