### ISSUE TITLE
Push the last release to support java 7 (1.57?) to Maven Central

### ISSUE THREAD

**Issue by garydgregory** [cbeust/jcommander#301]
Please push the last release to support java 7 (1.57?) to Maven Central.

**Comment by garydgregory** [comment]
ping?

**Comment by garydgregory** [comment]
ping?

**Comment by cbeust** [comment]
Sorry Gary, bit busy right now but I'll do my best.

-- 
Cédric

**Comment by jeremysolarz** [comment]
@cbeust I guess this can be closed since 1.58 is already pushed to maven central
@garydgregory what do you say?
