### ISSUE TITLE
help flag not properly working

### ISSUE THREAD

**Issue by alexkli** [cbeust/jcommander#305]
The [documentation](http://jcommander.org/#Help_parameter) has this example for help:

    @Parameter(names = "--help", help = true)
    private boolean help;

But the usage will print a default value for it, which doesn't make sense:

    Options:
      --help
  
        Default: false

So I tried around and changed it to an object:

    @Parameter(names = "--help", help = true)
    private Object help;

But now running with `--help` will give:

    Expected a value after parameter --help

Setting `arity = 0` didn't make a difference.

**Comment by spilth** [comment]
This sounds more like a request to not have the `--help` option print out its default in the usage output.

**Comment by alexkli** [comment]
You also have to implement it yourself, so I wonder if there is anything special about the `help = true` flag at all?

I'd suggest a general flag to suppress the default value output, for "action" options like `--help`.

**Comment by jeremysolarz** [comment]
@cbeust What's your opinion on that? Worth implementing?
Guess this should be a small change :)
Should there be a attribute to the annotation to suppress the usage output for the default value or should the parameter marked as help simply not show the default?

**Comment by cbeust** [comment]
Yes, just make an exception and don't display default values for boolean flags.

**Comment by jeremysolarz** [comment]
@cbeust for now I implemented it to only don't display defaults for `@Parameter`'s marked with `help=true`. Since I can imagine that people would need the display of defaults for other booleans. 

Still ok for you?

**Comment by jeremysolarz** [comment]
@cbeust I guess we can close this now :)
