### ISSUE TITLE
Passing the empty string as an argument

### ISSUE THREAD

**Issue by raxod502** [cbeust/jcommander#306]
It appears that JCommander drops arguments that happen to be empty, so that

```
$ java -jar foo.jar test ""
```

is effectively turned into

```
$ java -jar foo.jar test
```

Is this intended behavior? If so, how can I work around it reliably? For instance, I observed that

```
$ java -jar foo.jar test "''"
```

is interpreted as

```
$ java -jar foo.jar test ""
```

but this raises questions about how to include single quotes in the arguments, and what else might need to be escaped. I can't find the part of the source code that handles this conversion.

How can I be sure that my arguments, which might contain arbitrary sequences of characters, will be passed literally?

**Comment by raxod502** [comment]
Ah, just after I posted this I did in fact find the relevant part of the code:

```
  /**
   * Remove spaces at both ends and handle double quotes.
   */
  private static String trim(String string) {
    String result = string.trim();
    if (result.startsWith("\"") && result.endsWith("\"") && result.length() > 1) {
      result = result.substring(1, result.length() - 1);
    }
    return result;
  }
```

So it looks like I can achieve my desired functionality (arguments being processed literally no matter what they contain) by wrapping each of them in double quotes, and no escaping (even of double quotes, it looks like!) is necessary.

```
$ java -jar foo.jar '"<here goes my literal argument>"'
```

Is this correct?

**Comment by cbeust** [comment]
Are you sure this is the right interpretation? My immediate reaction was to
think that it's the shell that remove the empty string in your command
line, but that's just a guess.

-- 
Cédric

**Comment by raxod502** [comment]
Here's a quick demo showing that you can pass arguments in this way:

```
% cat count_arguments.sh
#!/bin/bash
echo $#
% ./count_arguments.sh a b c
3
% ./count_arguments.sh a b ""
3
```

**Comment by cbeust** [comment]
Indeed, so JCommander is removing them then.

-- 
Cédric

**Comment by raxod502** [comment]
Right. I'm 90% sure this behavior can be explained by the code I posted above (lines 519--528 of `JCommander.java`), since it's used to explicitly trim each argument in `parseValues` on line 634:

```
      String arg = args[i];
      String a = trim(arg);
```

Although, come to think of it, that still doesn't explain why the argument was dropped entirely when the trimming made it end up as the empty string. But the double quotes do seem to fix the problem in my testing so far (although there could definitely be other complicating factors, since my testing is occurring several libraries higher up in my dependency tree).

**Comment by jvstein** [comment]
The same piece of code is giving me problems with trailing spaces as well.

    $ java -jar foo.jar -param "arg-with-trailing-space "

I expect to get "arg-with-trailing-space " as the value, but instead I get "arg-with-trailing-space".

**Comment by raxod502** [comment]
As a workaround until this is fixed,

```
$ java -jar foo.jar -param '"arg-with-trailing-space "'
```

**Comment by jvstein** [comment]
Yes, thanks! I came to the same conclusion as you when reading the code and just thought I would document the related problem here.

**Comment by jeremysolarz** [comment]
@cbeust looks like the culprit is indeed in `parseValues`
In particular in 
```
else {
        //
        // Main parameter
        //
        if (! Strings.isStringEmpty(arg)) {
```
if I disable the empty string test all tests pass except
```
public void tmp() {
    class A {
      @Parameter(names = "-b")
      public String b;
    }
    new JCommander(new A()).parse("");
  }
```
that fails then with 
```
com.beust.jcommander.ParameterException: Was passed main parameter '' but no main parameter was defined
```
which seems logical.

Can you explain why the test for empty String was there?
Do you think the change (simply disabling this check) makes sense?

**Comment by jeremysolarz** [comment]
@raxod502 with the merged changes this shouldn't happen any more.

Can you please verify.

**Comment by raxod502** [comment]
@jeremysolarz Sorry for the slow response. In my testing the problem appears to be gone with the merged changes. Thanks!
