### ISSUE TITLE
Remove the reliance on prefixes to find options

### ISSUE THREAD

**Issue by cbeust** [cbeust/jcommander#321]
Options should be able to have any name and not be required to start with a prefix.

**Comment by jeremysolarz** [comment]
Note: This is related to #320, #245.

**Comment by cbeust** [comment]
Fixed in 1.61.

**Comment by LucCappellaro** [comment]
So we need to parse the [MainParameter](https://jcommander.org/#_main_parameter)s ourselves (detect options with prefixes) to reject unknown options? (https://github.com/cbeust/jcommander/issues/365)
Wasn't that the problem this tool wanted to solve in first place?
