### ISSUE TITLE
don't print usage with options if there are none

### ISSUE THREAD

**Issue by theonlygusti** [cbeust/jcommander#323]
Because of [this line](https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L991) the usage will always show options, even if there aren't any:

```java
private class CommandTemplate {
  @Parameters
  List<String> parameters = new ArrayList<>();
}

public static void main(String[] args) {
  CommandTemplate template = new CommandTemplate();
  JCommander jcommander = new JCommander(template);
  jcommander.setProgramName("main");
  jcommander.usage();
}
```

Running the above code will print `Usage: main [options]` even though there are no options.

**Comment by jeremysolarz** [comment]
@cbeust I guess a simple change, should this be implemented.

**Comment by jeremysolarz** [comment]
@cbeust ah just saw in latest commit a9bd34efc7d43e494cb5501b04c954a7a0185ebb this is fixed 😄

**Comment by theonlygusti** [comment]
@jeremysolarz I don't know if it is fixed or not yet, but it doesn't seem to have been deployed yet.

**Comment by jeremysolarz** [comment]
@theonlygusti as far I can see it's not pushed to maven. 

If you need the change right now you can clone the repo and build the JAR.

**Comment by cbeust** [comment]
Yes, not deployed yet.

**Comment by cbeust** [comment]
Done: 1.63 is now on JCenter.
