### ISSUE TITLE
Named arguments based on position

### ISSUE THREAD

**Issue by theonlygusti** [cbeust/jcommander#325]
Make it possible to create command syntaxes like

    main [command] [command options]
      Commands:
        set       Set an option.
          Usage: set <option> <value>

So that you can call

    main set brightness 100

and access it in-code like

```java
setCommand.option // "brightness"
setCommand.value // 100
```

**Comment by cbeust** [comment]
You can already do this by declaring an argument of `arity` 2 and parse it there, can't you?

**Comment by theonlygusti** [comment]
Not really, as I can't access it like `command.option`, which is what I'd like to be able to do, rather than getting it from some list.

**Comment by acostalima** [comment]
@theonlygusti could you please elaborate further on your use case(s)?

**Comment by theonlygusti** [comment]
Imagine I wanted to implement a move command to move files, I'd like to be able to create a command like:

    move <origin> <target>

and access the parameters through `command.origin` and `command.target` rather than having to access them from some list.

**Comment by cbeust** [comment]
Thinking out loud, this could be implemented with a new annotation, e.g. `@SubParameter`:

```
class MoveParameter {
  @SubParameter(order = 1)
  String origin;

  @SubParameter(order = 2)
  String destination;
}

class MyParameter {
  @Parameters(names = { "move" }, variableArity = 2)
  MoveParameters mv;
}
```

**Comment by cbeust** [comment]
I just implemented this, available in `master`:

```
  static class MvParameters {
    @SubParameter(order = 0)
    String from;
    @SubParameter(order = 1)
    String to;
  }

  @Test
  public void arity() {
    class Arguments {
      @Parameter(names = {"--mv"}, arity = 2)
      private MvParameters mvParameters;
    }

    Arguments args = new Arguments();
    new JCommander(args, new String[]{"--mv", "from", "to"});

    Assert.assertNotNull(args.mvParameters);
    Assert.assertEquals(args.mvParameters.from, "from");
    Assert.assertEquals(args.mvParameters.to, "to");
  }
```

**Comment by cbeust** [comment]
Deployed in 1.64.
