### ISSUE TITLE
Set custom text width for usage

### ISSUE THREAD

**Issue by theonlygusti** [cbeust/jcommander#326]
Invoking `usage()` always seems to return/print a string wrapped at 80.

Can we set our own wrapping for this?

**Comment by jeremysolarz** [comment]
Hi @theonlygusti,

according to @cbeust if you want to have a custom usage you can write your own.

Especially in easy cases (without @Command sub-objects) that should be quite easy with parsing the existing annotations.

Best,

JS

**Comment by theonlygusti** [comment]
@jeremysolarz is @Command a real thing? I've been using @Parameters...

But your suggestion doesn't fix the problem, I feel like wrapping at custom widths wouldn't be a very difficult thing to implement. Also, I like that the default `usage` goes through all defined commands/options/etc. and prints them all. From what I understand, to incorporate this into my own usage, if I were to write it myself, this would be very difficult.

**Comment by jeremysolarz** [comment]
@theonlygusti correct meant @Parameters of course.

**Comment by tze** [comment]
For anyone else who might be running into this, too: The default column width of 79 chars is actually configurable via [JCommander.setColumnSize](https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L1273).

**Comment by jeremysolarz** [comment]
Thanks @tze for finding this. Than we can close this ticket.
