### ISSUE TITLE
jcommander.getParsedCommand() errors if no command parsed

### ISSUE THREAD

**Issue by theonlygusti** [cbeust/jcommander#327]
It looks like `jcommander.getParsedCommand()` throws an error if no command has been parsed.

I feel like returning `null` or an empty string would make more sense, rather than forcing us to use a lot of `try`/`catch` blocks.

**Comment by acostalima** [comment]
Does `parse()` throws already if no valid command is parsed? If it doesn't, I think it should.
If `parse()` is successful, i.e., if anything is parsed and validated, then `getParsedCommand()` should always be successful with the guarantee that the parsed command is always returned and no exceptions thrown.

**Comment by jeremysolarz** [comment]
@theonlygusti, @acostalima 

just tested and both tests pass wit latest JCommander

```
@Test
  public void parseWithNoCommand() {
    CommandMain cm = new CommandMain();
    JCommander jc = new JCommander(cm);
    CommandAdd add = new CommandAdd();
    jc.addCommand("add", add, "xx");

    jc.parse();
  }

  @Test
  public void getParsedCommandWithNoCommand() {
    CommandMain cm = new CommandMain();
    JCommander jc = new JCommander(cm);
    CommandAdd add = new CommandAdd();
    jc.addCommand("add", add, "xx");

    jc.getParsedCommand();
  }
```

I have the feeling that the behavior described by @acostalima is correct

@cbeust what do you say, should JCommander throw when no command is given?

**Comment by cbeust** [comment]
Throwing is how JCommander signals errors, not returning `null`.

**Comment by acostalima** [comment]
Just want to add something else up here. Following what @cbeust said, in the particular case of `parse()`, wouldn't it be better fit if it throws a checked exception in the failure scenario? This way, the client will explicitly aware that `parse()` can fail (at compile time) and has to handle the exception to recover. Concerning `getParsedCommand()`, I think it should never fail if `parse()` is successful as I mentioned in my previous comment. If `getParsedCommand()` is called before `parse()`, I'd say that an `IllegalStateException` should be thrown instead.

@cbeust @jeremysolarz what do you think?

**Comment by jeremysolarz** [comment]
@acostalima as long as the commands are not required `parse` as well as `getParsedCommand` will not throw which seems like expected behavior.

The thing is you only know if there will be an exception during runtime. Once `JCommander` has parsed the annotations.

**Comment by acostalima** [comment]
@jeremysolarz I know that. I was just suggesting what, at least in my view, would be an small enhancement to the API design, to help and guide the client on its usage,
