### ISSUE TITLE
http://jcommander.org/#_parameter_delegates wrong markup

### ISSUE THREAD

**Issue by RettPop** [cbeust/jcommander#328]
"JCommander configuration in order to use the delegate:" phrase at the end of "21. Parameter delegates" chapter was marked as part of the code block. 

![screenshot from 2017-02-13 10 26 41](https://cloud.githubusercontent.com/assets/2702414/22877877/b6548428-f1d7-11e6-9411-3a5dc83c0194.png)

**Comment by cbeust** [comment]
Fixed, thanks!
