### ISSUE TITLE
No local.properties

### ISSUE THREAD

**Issue by paulcwarren** [cbeust/jcommander#335]
Just a very minor issue but there is no local.properties checked in which makes Eclipse Gradle plugins barf as they try to parse your publishing.gradle file.

**Comment by paulcwarren** [comment]
I simple created an empty local.properties in my root directory.  I was going to PR it in but then I noticed it is git ignored so I guess this was a deliberate decision.  Therefore just noting in case it is useful for others.

**Comment by cbeust** [comment]
Yes, it is deliberate: this file should never be checked in since it typically contains authentication information.
