### ISSUE TITLE
Documentation missing for getting unknown args

### ISSUE THREAD

**Issue by lukehutch** [cbeust/jcommander#340]
The documentation at jcommander.org is missing a description of how to get unknown args. (I had to read the source code to see how this worked.)

It's not enabled by default, so it would be helpful if the sourcecode showed an example of how to enable unknown args, and then how to get them after known args have been parsed.

**Comment by cbeust** [comment]
Can you show the code you used to get these unknown args? I'll include it in the doc.

Thanks.

**Comment by lukehutch** [comment]
My bad, what I was trying to get `unknownOptions` to do is actually solved by the "main parameter" option, of type `List<String>`. (That's what I thought unknown options was for, but it's already solved.)
