### ISSUE TITLE
Add an ability to limit count of main parameters

### ISSUE THREAD

**Issue by baev** [cbeust/jcommander#344]
I trying to implement the following command: 

```sh
$ program <argument>
```

The only one argument is allowed, but it seems like there is no way to limit count of main parameters.

**Comment by cbeust** [comment]
Why not simply assert that yourself after the parsing?

**Comment by baev** [comment]
> Why not simply assert that yourself after the parsing?

I did, that it seems like a hack

**Comment by baev** [comment]
That is the only validation I can't perform using JCommander. I tried to use value validator but it is broken https://github.com/cbeust/jcommander/issues/269
