### ISSUE TITLE
Display of default values of custom types in help

### ISSUE THREAD

**Issue by sschuberth** [cbeust/jcommander#347]
I'm using a [listConverter](http://jcommander.org/#list-value) to turn a list of string parameters into a list of custom types. The default value of the parameter is a pre-defined list of these custom types. In the [usage](http://jcommander.org/#_usage), the default value is displayed as a list in the form

    Default: [CustomClass1@7106e68e, CustomClass2@7eda2dbb, CustomClass3@6576fe71]

As this is not nice to read, I was looking for a way to map custom classes to string, i.e. the opposite of a `listConverter`. Of course, I could solve the problem by overriding `toString` for the custom classes to match the input strings to `listConverter`, but I was wondering whether there is a more "symmetric" solution to `listConverter`.

**Comment by cbeust** [comment]
Implementing `toString()` is the way to go.
