### ISSUE TITLE
Clear label on which version to use for which JDK and other doc issues

### ISSUE THREAD

**Issue by agentgt** [cbeust/jcommander#350]
I have to say I'm fairly confused at release versioning and documentation of JCommander.

From what I gather because of a recent changes to the build system and general state the project is now doing rolling releases (otherwise it boggles my mind that JCommander.Builder visibility of friendly was released to maven central).

This is fine but it would be nice if:

*  You should be able to get to older versions of the documentation that corresponds with the release. The current doc says `1.60` but the API examples are not even in `1.60`.
* Perhaps mark some releases as less stable (pick some scheme.. maybe build meta or odd minor numbers etc).

Also it would be nice if it was clear which version to use if you are using JDK 7. I basically spent a couple of minutes looking at git tags to figure that out and then what was actually in maven central.

Documentation I was looking at was here http://jcommander.org/ .

I hate complaining without doing a pull request but I'm not sure what or how it should be corrected.

**Comment by cbeust** [comment]
Hi Adam,

Sorry for the confusion.

The JDK 1.8 release was a mistake, JCommander should be 1.7 and I'm going to try to keep it this way for as long as I can.

I always release to JCenter first and then I sync to  Maven Central, however that sync is flaky so I sometimes have to wait and try again later (which sometimes ends up with versions being skipped in Maven Central. This should have little impact on users as long as they have both JCenter and Maven Central in their build file.

**Comment by agentgt** [comment]
Thanks for the clarification! The JCenter explains how I was able to get other versions (I forgot I had JCenter repository included).

**Comment by cbeust** [comment]
Any other questions or can I close this issue?

**Comment by agentgt** [comment]
Nope.
