### ISSUE TITLE
Set description for command, but not for option

### ISSUE THREAD

**Issue by PashaTurok** [cbeust/jcommander#352]
For every command I have a concrete class which implements certain interface. For example:

```
public class FooCommand implements Command{
    @Parameter(names = {"-?","--help"}, description = "display this help",help = true)
    private boolean helpRequested = false;
 }

```
I have foo-command, boo-command, lala-command. However, all these commands are separate and are not within one main command (by other words this is not like git clone ...). This is the way I get usage

```
 JCommander jCommander=new JCommander(command, args);
 jCommander.setProgramName(commandName);//for example foo-command
 StringBuilder builder=new StringBuilder();
 jCommander.usage(builder);
```

And this is the usage message I get:

```
Usage: foo-command [options]
  Options:
    -?, --help
      display this help
```

However I need to add description to command (but not to option). For example I want to get such usage message:

```
Usage: foo-command [options] - This command is used as base foo
  Options:
    -?, --help
      display this help
```

To get it I do this way:
```
public class FooCommand implements Command{
    @Parameter(names = {"-?","--help"}, description = "display this help",help = true)
    private boolean helpRequested = false;
   @Parameter(description = "This command is used as base foo")
    private String usage=null;//this field is only for setting parameter
 }
```
The code seems to work, but I don't like that there is a field usage that is not used. Maybe it is better to add support for such cases?

**Comment by acostalima** [comment]
Did you have a look at the official [docs](http://jcommander.org/#_more_complex_syntaxes_commands)?

**Comment by PashaTurok** [comment]
Yes, I've read official docs. And I tried :
```
@Parameters(commandDescription = "Add file contents to the index")
public class FooCommand implements Command{..}
```
However, at this case command description is not added at all. Please, note, that I don't use Main command like (git). All my commands are independent and are not within one command. I use JCommand 1.66

**Comment by acostalima** [comment]
Ok. I was mislead by your code snippet above. In that case, if the command description is not being printed out, then I guess this is non-intended behavior. @cbeust re-open?

**Comment by cbeust** [comment]
I can't reproduce the problem:

```
        @Parameters(commandDescription = "This command is used as base for")
        class FooCommand {
        }

        FooCommand a = new FooCommand();
        JCommander.newBuilder()
                .addCommand("--a", a)
                .build()
                .usage();
        }
```

displays:

```
Usage: <main class> [command] [command options]
  Commands:
    --a      This command is used as base fo
      Usage: --a
```

**Comment by PashaTurok** [comment]
That's is wrong. Please, pay attention at your usage. You have a main command and subcommands (which you addCommand()). In your example --a is subcommand. Your example is like git. 
However, I am speaking quite about different usage. I don't have main command and subcommands. All my commands are at the same level and there is no main command. It is not(!) like git. Please, read carefully what I wrote above, because every time I say the same but later you again think in "git" like manner.

**Comment by PashaTurok** [comment]
I will explain on example. This is current behavior:

```
Usage: <main class> [command] [command options]
  Commands:
    --foo      This command is used as base foo  
      Usage: --foo

```
This is the behavior I am speaking about

```
Usage: foo-command [options] - This command is used as base foo
  Options:
    -?, --help
      display this help
```
In the second example there is no any main command and subcommands. It is just a single (standalone,independent, plain etc) command with simple description. Please, any feedback.

**Comment by PashaTurok** [comment]
Could anyone say if there is any chance that this issue will be reopened or I just wasting my time posting these messages which seem to be ignored?

**Comment by jeremysolarz** [comment]
Dear @PashaTurok,

A behavior as explained by you is indeed not possible at the moment.

I pushed a branch to my fork in branch [issue-352-program-description](/jeremysolarz/jcommander/tree/issue-352-program-description) to show how to do it but I am not sure if the changes are clear enough to make it into JCommander.

Best,

JS

**Comment by PashaTurok** [comment]
@jeremysolarz Thank you for your answer and attempt. I didn't answer so long because I lost any hope to get any answer. Just today I decided to take a look. 

Maybe what I need is not possible, maybe. But I don't think then this case issue must be simply closed and all messages must be ignored. To tell the truth I don't understand it.

**Comment by jeremysolarz** [comment]
Dear @PashaTurok,

As you can see it is possible through a change to JCommander. 

But it's up to @cbeust if he considers the change necessary or not.

😄

**Comment by raubel** [comment]
Having the possibility to display a global description of the command along with the help message.
I also miss this feature a lot!
