### ISSUE TITLE
Enable OSGI support in official builds

### ISSUE THREAD

**Issue by PashaTurok** [cbeust/jcommander#354]
JCommander 1.48 which I downloaded from maven repo supports OSGi. However, version 1.58, 1.60, 1.69 don't. I suggest continue OSGI support in new versions.

**Comment by cbeust** [comment]
I restored the OSGi manifest in 1.71, which I just deployed to JCenter.

It's a new implementation so let me know if this manifest is not working (and what's missing) and I'll fix it.
