### ISSUE TITLE
Example code from documentation doesn't compile: JCommander.Builder is defined in an inaccessible class or interface

### ISSUE THREAD

**Issue by rohanliston** [cbeust/jcommander#355]
I'm trying to compile an example copied directly from the documentation in a clean project but am getting the following errors:

Error:(17, 17) java: addObject(java.lang.Object) in com.beust.jcommander.JCommander.Builder is defined in an inaccessible class or interface
Error:(18, 17) java: build() in com.beust.jcommander.JCommander.Builder is defined in an inaccessible class or interface

```
package au.com.myorg.mytool.cli;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;

class Main
{
    @Parameter(names={"--length", "-l"})
    int length;
    @Parameter(names={"--pattern", "-p"})
    int pattern;

    public static void main(String ... argv) {
        Main main = new Main();

        JCommander.newBuilder()
                .addObject(main)
                .build()
                .parse(argv);

        main.run();
    }

    public void run() {
        System.out.printf("%d %d", length, pattern);
    }
}
```

Using OpenJDK 8, Gradle, and `compile "com.beust:jcommander:1.66"` (but get the same error with a few other versions I tried).

**Comment by rohanliston** [comment]
Looks like it was fixed in https://github.com/cbeust/jcommander/commit/dbf7dbd338b42532e12f513263053a2b352cae02

Changed my version to 1.69 and it now compiles. Might be worth updating http://jcommander.org/#_download, as the Gradle/Maven instructions still have old version numbers in them despite the docs using the newer API.

**Comment by cbeust** [comment]
Done.
