### ISSUE TITLE
AnnotationTypeMismatchException

### ISSUE THREAD

**Issue by SnapshotsOfMinds** [cbeust/jcommander#356]
I have been doing some work on an application that is now using JCommander. I have created a FileValidator class that implements the IParameterValidator. All the class does is validate the file exists. When running through eclipse using the latest build for JCommander, everything works as expected. When I build my application's JARs and run it via command line, I get an AnnotationTypeMismatchException. I have verified that I do not see this error with version 1.64 of JCommander at all but I do see it in both 1.69 and 1.71. My applications JARs are built through maven, if that has any relevance.

The error I am seeing on command line is as follows:
> C:\Temp\demo>java -classpath "target/*" Application create --file="C:\Temp\demo\test.txt"
> Exception in thread "main" java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.Class[] com.beust.jcommander.Parameter.validateWith() (Found data of type class java.lang.Class[class FileValidator])
>         at sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(Unknown Source)
>         at sun.reflect.annotation.AnnotationInvocationHandler.invoke(Unknown Source)
>         at com.sun.proxy.$Proxy1.validateWith(Unknown Source)
>         at com.beust.jcommander.WrappedParameter.validateWith(WrappedParameter.java:55)
>         at com.beust.jcommander.ParameterDescription.validateParameter(ParameterDescription.java:330)
>         at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:233)
>         at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:848)
>         at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:823)
>         at com.beust.jcommander.JCommander.parseValues(JCommander.java:676)
>         at com.beust.jcommander.JCommander.parse(JCommander.java:312)
>         at com.beust.jcommander.JCommander.parseValues(JCommander.java:740)
>         at com.beust.jcommander.JCommander.parse(JCommander.java:312)
>         at com.beust.jcommander.JCommander.parse(JCommander.java:291)
>         at Application.main(Application.java:48)

The source code for the FileValidator class is:
```java
public class FileValidator implements IParameterValidator {
    @Override
    public void validate(String name, String value) throws ParameterException {
        if (!Files.exists(Paths.get(value))) {
            throw new ParameterException("FILE_DOES_NOT_EXIST");
        }
    }
}
```

The command itself is defined as:
```java
@Parameter(names = "--file", validateWith = FileValidator.class, required = true, description = "The properties file containing setup information.")
private Path propertiesFile = Paths.get("");
```

**Comment by cbeust** [comment]
Never seen this exception before, that's a first.

So far, no luck reproducing this problem, here is the code I'm using. Can you provide a project that I can use to reproduce this? What command line are you running exactly? I suspect some classpath problem.

```
    public static void main(String[] args) {

        class FileValidator implements IParameterValidator {
            @Override
            public void validate(String name, String value) throws ParameterException {
                if (!Files.exists(Paths.get(value))) {
                    throw new ParameterException("FILE_DOES_NOT_EXIST");
                }
            }
        }

        class Args {
            @Parameter(names = "--file", validateWith = FileValidator.class, required = true,
                    description = "The properties file containing setup information.")
            private Path propertiesFile = Paths.get("");
        }

        JCommander.newBuilder()
                    .addObject(new Args())
                    .build()
                    .parse("--file", "README.markdown");
    }
```

**Comment by SnapshotsOfMinds** [comment]
I tried to create a minimum working project on my personal Git that I could send you a link for but it does not experience the same error so I don't think that would be much help. I can't give the actual project link since it is on a private Github server. I did, however, try more troubleshooting.

I put in "jcommander.setVerbose(1);" in the project where I am seeing the exception to see how far the command parsing is actually getting and the exception stopped occurring. I commented out the line and the exception still did not display again. I went another step further as well and configured a remote debug of the JAR via command line. This still did not reproduce the error.

For now, you can just ignore this issue. If it ends up reoccurring, I can try running the remote debug and setting JCommander's verbosity again to see if I can catch it in the act and re-post at that time.

**Comment by cbeust** [comment]
Thanks for investigating, don't hesitate to reopen if you can provide a reproducible sample.
