### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by pathum999** [cbeust/jcommander#357]
I am trying to configure selenium webdriver for chrome. and when run below command gives the error 

Command : java - jar selenium-server-standalone-3.4.0.jar chromedriver.exe

Error : Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'chromedriver.exe' but no parameter was defined

**Comment by acostalima** [comment]
@pathum999 usage of main parameter is described in the [docs](http://jcommander.org/#_main_parameter).

**Comment by acostalima** [comment]
@cbeust I think you can close this one as well. It seems to be wrong usage of JCommander.
