### ISSUE TITLE
@Parmeter "order" not found in 1.7

### ISSUE THREAD

**Issue by RileyR387** [cbeust/jcommander#363]
In version 1.69 the "order" parmeter for usage() ordering is functioning. It's not found in 1.7, and 1.7+ isn't in maven yet so I'm not sure if it's fixed upstream or not.

**Comment by cbeust** [comment]
1.7 is an earlier version than 1.69.

Try 1.72.

**Comment by RileyR387** [comment]
That makes sense. https://repo.maven.apache.org/maven2/com/beust/jcommander/ is sitting at 1.69. 
The lexical sort for the 1.7 release gave me a brain fart after i copied your pom in the doc for v1.7.

I'll wait for the changes to come downstream :) 1.69 serves me just fine.

Thanks a ton!
