### ISSUE TITLE
maven repo update to 1.72?

### ISSUE THREAD

**Issue by thisiscam** [cbeust/jcommander#366]
As titled, will it happen any time soon?

**Comment by cbeust** [comment]
Done, it should appear on Maven Central soon.

**Comment by juewe** [comment]
? https://github.com/cbeust/jcommander/releases mention 1.71? Where is 1.72...?

**Comment by cbeust** [comment]
http://search.maven.org/#artifactdetails%7Ccom.beust%7Cjcommander%7C1.72%7Cjar

**Comment by juewe** [comment]
Sorry, yes, i've seen that! But i thought, maybe my mistake, that one it should be also noted somewhere here on github (see link)? Am i wrong? Im a bit confused, since it's not obvious for me, in which version the commits are implemented. Am i missing something?
