### ISSUE TITLE
Nested subcommand

### ISSUE THREAD

**Issue by kakawait** [cbeust/jcommander#374]
I would know if it's possible to get _nested_ command like following example:

```
command sub-command1 sub-command2
```

Today there is `addCommand()` API that allow you to define a command but I didn't find a way to defined a nested command... We may (didn't try) simulate the behavior by calling _JCommander_ recursively but we will loose some feature like global `usage()` and still be a hack.

You can find more example in similar project called `picocli` http://picocli.info/#_nested_sub_subcommands

---

If I'm wrong and is already possible we may upgrade documentation.

**Comment by imedina** [comment]
Hi,

I think the answer is yes,  you can see an example in my project at:

https://github.com/opencb/opencga/blob/develop/opencga-app/src/main/java/org/opencb/opencga/app/cli/main/OpencgaCliOptionsParser.java#L77

you just need to add a command (L77) and get that command and nested commands (L78 and L79). The result is something like:

![image](https://user-images.githubusercontent.com/1427327/31590629-74857abc-b20b-11e7-9ce9-bcf645af51c5.png)

I hope that helps.
