### ISSUE TITLE
Spaces not allowed in @DynamicParameter value

### ISSUE THREAD

**Issue by redcue** [cbeust/jcommander#383]
```
@DynamicParameter(names = { "-uv",
		"--usrvar" }, description = "someDesc")
private Map<String, String> userVariables = new HashMap<String, String>();
```
This implementation does not support `app do something -uv test="this awesome space"` as of 1.72

with error:
```
Jul 05, 2017 4:06:00 PM com.braintribe.product.rat.firectrl.recipe.runner.CommandLineInterface
SEVERE: Only one main parameter allowed but found several: "something" and "awesome"
```

**Comment by cbeust** [comment]
I suspect this is dependent on the shell you're using. Some will break down the string in double quotes into individual words while others will pass the whole sentence to the process.

**Comment by redcue** [comment]
Have to apologize... I don't quite understand.

Tested this in bash and zsh. Same behavior.

**Comment by redcue** [comment]
Sorry... was indeed a shell problem. Wrapper sh script for calling the CLI didn't `eval` the full command.

Ty
