### ISSUE TITLE
Add Automatic-Module-Name

### ISSUE THREAD

**Issue by jodastephen** [cbeust/jcommander#385]
To support other projects in Java 9, this low-level library needs to have `Automatic-Module-Name` added to the jar file manifest. eg. the MANIFEST.MF file needs to have the line:

    Automatic-Module-Name: com.beust.jcommander

As an alternative, a proper `module-info.java` file could be added, something like:

    module com.beust.jcommander {
        exports com.beust.jcommander; 
        exports com.beust.jcommander.converters; 
        exports com.beust.jcommander.defaultprovider; 
        exports com.beust.jcommander.validators; 
    }

assuming that `com.beust.jcommander.internal` is not meant to be exposed. This may require new features in Kobalt, whereas I assume adding a manifest entry does not.

**Comment by cbeust** [comment]
Thanks, Stephen. Do you want to send a PR with that `module-info.java` file?

**Comment by cbeust** [comment]
@rbjorklin Unless I'm missing something, `module-info.java` is present in the distribution:

https://github.com/cbeust/jcommander/blob/master/module-info.java

Do you need something else?

**Comment by jodastephen** [comment]
So, to be useful, the `module-info.java` file has to be compiled into `module-info.class` (on Java 9) and placed at the root of the jar file. The Maven instructions are [here](https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html). No idea what exactly you'd need to do for Kobalt or Gradle. Note that as per the Maven instructions, the jar file can still work on JDK 8. The trick is the `--release` flag of Java 9. Here is a project with the correct [Maven setup](https://github.com/ThreeTen/threeten-extra/blob/master/pom.xml#L642).

**Comment by cbeust** [comment]
Thanks @jodastephen, I'm looking into it.

**Comment by cbeust** [comment]
I'll probably cut a 2.0.0-RC1 release to break cleanly from the Java 7 compatible version.

**Comment by cbeust** [comment]
Done:

http://jcenter.bintray.com/com/beust/jcommander/2.0.0-RC1/

Let me know how it works for you @rbjorklin @jodastephen

**Comment by jodastephen** [comment]
Looking at the class file of `DefaultUsageFormatter.class` in a hex editor, it has the Java 9 classfile version (hex 35).

I think you want the classfile version to be Java 8 so your project is still Java 8 compatible, with just `module-info.class` as Java 9. To make this work with Maven, you have to compile the whole project twice - first with Java 9 including `module-info.java`, then using the Java 9 compiler as `--release 8` excluding `module-info.java`. Its a pain but it does work.

**Comment by cbeust** [comment]
Ah, ok. Yuck. What's the purpose of that, remain at least Java 8 compatible?

**Comment by jodastephen** [comment]
Yes. Java 8 is the LTS release (long term support). Most users are going to remain on 8 until at least 11 comes out. So, I think its in your interest to support Java 8 for a while yet. (Java 9 is obsolete in six weeks, and most users can't move fast enough to keep changing major Java versions)

As above, adding a `module-info.class` to a Java 8 jar file isn't straightforward, but it is possible. (I've done it on some of my projects, see link above).
