### ISSUE TITLE
Combining options into a single argument

### ISSUE THREAD

**Issue by rddunphy** [cbeust/jcommander#389]
Is there a way to allow combining multiple flags into a single argument, e.g. so that `-la` can be parsed as `-l -a`?

**Comment by cbeust** [comment]
No, but that's pretty easy to do yourself after JCommander has done its parsing, so you can reflect the fact that both flags were set in a field of your arg class.

**Comment by rddunphy** [comment]
Okay, thanks. That will be fine for my project, where I only have a couple of arguments. The reason I asked is that if you have large numbers of boolean arguments, this approach quickly becomes unmanagable - e.g. with five arguments, there are 320 ways to choose two or more flags.

**Comment by acostalima** [comment]
> Okay, thanks. That will be fine for my project, where I only have a couple of arguments. The reason I asked is that if you have large numbers of boolean arguments, this approach quickly becomes unmanagable - e.g. with five arguments, there are 320 ways to choose two or more flags.

@rddunphy you still need to know which flags were specifically set, right?

**Comment by rddunphy** [comment]
Right, but with boolean options you don't generally care about the order. For example, `ls -lahXR` has the same result as `ls -RXhla`. To catch all of these arguments you would need a field something like this, as well as similar fields for every possible subset of options: 
`@Parameter(names={"-ahlRX", "-ahlXR", "-ahRlX", "-ahRXl", .....})
private boolean ahlRX;`

**Comment by acostalima** [comment]
Ok, now I have a clear understanding of the issue. What you propose seems illogical and also a misuse of JCommander. What if the user passes -lahR, -Ra or -X? You still want to know which flag were set and those that weren't. Even if JCommander supported such argument passing style, the point @cbeust was trying to make is you have to include boolean fields for each and every flag you need:

```
@Parameter(names = { "-a"})
private boolean a;
@Parameter(names = { "-l"})
private boolean l;
@Parameter(names = { "-h"})
private boolean h;
...
```
If your use case requires to check if the user passed all of them, it is easy to do it using the AND operator.

**Comment by acostalima** [comment]
@cbeust would you be willing to accept a PR to add support for combined argument passing for short options?

**Comment by rddunphy** [comment]
Right, sorry - I may not have explained that very well. What I'm looking for is the behaviour you described, where there is a boolean field for each argument, but combinations of arguments can be entered (without requiring a field for each combination). So, if the user enters -lahR, then l, a, h, and R will be set to true, and any other boolean fields will be false. (This is the behaviour you get from ls and other common UN*X terminal applications.)

**Comment by rddunphy** [comment]
I've had a go at implementing this in PR #393

**Comment by acostalima** [comment]
@rddunphy Precisely. :) Thanks for the PR.
