### ISSUE TITLE
Using <init>(string) or Class.valueOf(string) in addition to IStringConverter 

### ISSUE THREAD

**Issue by dibog** [cbeust/jcommander#395]
If a @Parameter annotation is attached to a field which is not a a basic type like int, string, etc. JCommander tries to find a compatible IStringConverter to convert from string to the acutal type.

If JCommander doesn't find any such converter he returns an error message to the console.
It would be nice if JCommander instead would try to check if that type has a constructor which takes a single string, or if that type has a static method called "valueOf" which takes a single string and use the result to initialize that field.

Or does this already exists and I have missed it?

**Comment by dibog** [comment]
Is there no feedback on this issue or interest on the pull request?
I think it is a nice improvement which allows the usage of richer data types for parameters.

**Comment by jeremysolarz** [comment]
@dibog just a tiny remark. For the future please discuss PRs first before implementing them.
Otherwise this could lead to frustration if your PR doesn't get merged.

@cbeust what do you say. Thinks like a nice / reasonable improvement.

**Comment by dibog** [comment]
@jeremysolarz Thanks for your feedback. I'm happy to still discuss my proposal. If you think there should be changes (like the name of the static method or the priority between the static method and the constructor call) I happy to change my code in this regard.

**Comment by cbeust** [comment]
I'm not a fan of magic names, especially when there is an existing, statically typed way to provide this functionality (`IStringConverter`).

Going to close this unless there's a strong case.

**Comment by dibog** [comment]
Here my arguments, you have to decide if they are strong or not :-)

a) Using the constructor or the static valueOf method avoids creating unnecessary code.
These extra code, which also leads to lots extra arguments in the @Parameter annotations,
leads to the situation that most people just go with using Strings and they convert to the correct
type somewhere in the command line program. The conversion there could fail and every developer will treat this differently. That is not very user friendly, neither to the developers nor to the actual users of the command line tool and leads to extra effort for everybody who wants to use rich data types.

b) Using the constructor or a specific static method is a well established way used in the Java SDK, e.g.
URL: https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#URL(java.lang.String)
File: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#File(java.lang.String)
ZipFile: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#File(java.lang.String)
Integer: https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#valueOf(java.lang.String)
So nothing really new.

c) Statically typed: The constructor is per definition statically typed and the code I used will only
take the static method into account if it returns a value of the correct static type and is such type safe.

d) My proposal would only act as fallback method which is used when no other converter or converter
factory exists.

The proposal would behave in a very intuitive way and is at the same time type safe and reduces boiler plate code.

Best regards,
Dieter

**Comment by dibog** [comment]
@cbeust and @jeremysolarz Are the arguments strong enough?

**Comment by simon04** [comment]
`valueOf()` does not seem to be used consistently in the Java ecosystem. For instance, [Auto Value](https://github.com/google/auto/blob/master/value/userguide/index.md) is suggesting `create()`, and various classes introduced with Java 8 – `Optional`, `Stream` – use `of()`.

With lambdas in Java 8 and the `IStringConverterInstanceFactory`, writing a converter for `valueOf()` (or any other static function) is a oneliner plus providing full IDE support. Since JCommander requires Java 8 anyways, I don't see much gain in the magic handling of `valueOf()` functions

**Comment by cbeust** [comment]
Agreed, closing.
