### ISSUE TITLE
Autocomplete feature 

### ISSUE THREAD

**Issue by wbari** [cbeust/jcommander#398]
I tried to find information about autocomplete with jCommander but unfortunately not of much help. Is there any feature request like this in queue or there is someway to make it work with jc 1.58 or newer?

Thanks & Cheers,
Wasim

**Comment by cbeust** [comment]
I don't see how autocomplete could be performed by JCommander, it's a shell issue.

**Comment by cbeust** [comment]
Ah ok, you mean an interactive shell.

**Comment by imedina** [comment]
I think he meant shell autocomplete, and you are right, this is a shell issue. FYI I work with @wbari last week to implement a a generic method to create shell completion scripts from a JComander Object, it works with commands and subcommands (two levels), code at:

https://github.com/opencb/java-common-libs/blob/develop/commons-lib/src/main/java/org/opencb/commons/utils/CommandLineUtils.java#L106

the generated scripts can then be copied into `/etc/bash_completion.d/`. We have tried with three different CLIs and it works fine.

Thanks for your great work!
