### ISSUE TITLE
Javadoc jar empty on maven repository

### ISSUE THREAD

**Issue by jonbarksdale** [cbeust/jcommander#404]
Steps:
1. Go to search.maven.org
2. search for jcommander
3. download the javadoc.jar for com.beust jcommander (most recent as of this ticket was 1.7.2)

Expected:
javadoc jar should contain javadoc 

Actual: 
javadoc jar contains nothing

**Comment by cbeust** [comment]
Fixed, 1.75 now available on Maven Central:  https://search.maven.org/artifact/com.beust/jcommander/1.75/jar
