### ISSUE TITLE
Add Autocompletion!

### ISSUE THREAD

**Issue by aadrian** [cbeust/jcommander#406]
Hi,

Please add command line auto-completion too.

Thank you.

**Comment by imedina** [comment]
FYI this was briefly discussed recently at #398 

In the 4th comment you will find a link to a generic method for creating bash auto-completion scripts, maybe that is useful to you.

**Comment by aadrian** [comment]
@imedina not really. This solution  https://github.com/remkop/picocli just works really well. I was hoping for something similar in JCommander too.
