### ISSUE TITLE
Trimming parameters

### ISSUE THREAD

**Issue by tavoda** [cbeust/jcommander#417]
Hello,
why are you trimming parameters? I don't know how on windows but on Unix is definitely wrong idea. If I run program like:
```
Tool -L abc     -P def
```
than parameters are trimmed by shell and I get "-L", "abc", "-P", "def", when I would like to add space I have to run:
```
Tool -L 'abc '    -P def
```
And I will get parameter with space "abc " that's intention. It's common practice on unix. Nobody (on unix) will use '"abc "' specially if you want use some shell variable as parameter instead of simple "this$var1" I have to use something like '"this'$var1'"'.
Is it necessary for windows? Can we avoid trim() on Unix (via System.getProperty("os.name"))? I can provide patch.

**Comment by cbeust** [comment]
Can you show a JCommander example where this is happening?

**Comment by tavoda** [comment]
It's happening in JCommander.trim() function. If I declare field like:
```
	@Parameter(names = {"-L", "--replace-new-line"}, description = "Char used for replacing new line in value")
	protected String escapeNl;
```
and start it from command line with `java -jar myTool.jar -L ' '` I will get empty string ("") instead of space in escapeNl.

**Comment by cbeust** [comment]
Fixed in the next version.

**Comment by tavoda** [comment]
I looked at fix and I'm not sure how it will work on windows (cmd.exe). For unix/linux this is OK however I'm not sure how it will for on windows because cmd.exe is not doing parameter processing and removing quotes ("/') is maybe necessary because cmd.exe will send parameters AS IS provided on command line together with quotes. I have no environment to test on windows :-/.
