### ISSUE TITLE
Missing directory entries in jcommander jar

### ISSUE THREAD

**Issue by dipak-pawar** [cbeust/jcommander#430]
### Jcommander Version
> 1.72
>  1.66

### Description:
- Run  `jar -tf jcommander-1.72.jar`
- All entries for directories are not packaged in the jar. This causes a problem while trying to get resources from classpath.
- Latest released testng jar is bundled with `com.beust:jcommander:jar:1.66`. I have opened similar issue for TestNG yesterday https://github.com/cbeust/testng/issues/1677
- In particular this causes problem in Arquillian integration with testng. See [issue#comment](https://github.com/cbeust/testng/issues/1513#issuecomment-356036638)

### Expected behavior
```bash
META-INF/
META-INF/MANIFEST.MF
com/
com/beust/
com/beust/jcommander/
com/beust/jcommander/ParametersDelegate.class
com/beust/jcommander/IStringConverterInstanceFactory.class
com/beust/jcommander/FuzzyMap$IKey.class
com/beust/jcommander/MissingCommandException.class
com/beust/jcommander/internal/
com/beust/jcommander/internal/Maps.class
...
```

### Actual behavior
```bash
com/beust/jcommander/converters/BaseConverter.class
com/beust/jcommander/converters/BigDecimalConverter.class
com/beust/jcommander/converters/BooleanConverter.class
com/beust/jcommander/converters/CharArrayConverter.class
com/beust/jcommander/converters/CommaParameterSplitter.class
com/beust/jcommander/converters/DefaultListConverter.class
com/beust/jcommander/converters/DoubleConverter.class
com/beust/jcommander/converters/EnumConverter.class
com/beust/jcommander/converters/FileConverter.class
com/beust/jcommander/converters/FloatConverter.class
...
```
### Test case sample
> https://github.com/dipak-pawar/jcommander-classloading

**Comment by krmahadevan** [comment]
@dipak-pawar - Thanks. I guess the problem in both the issues is the build tool kobalt.

@cbeust - can you please help ?

**Comment by cbeust** [comment]
Should be fixed in JCommander 1.73.

**Comment by manovotn** [comment]
@cbeust Hi, is there any time estimation on when jcommander 1.73 gets released (and ultimately, when TestNG gets it and is released)?

**Comment by cbeust** [comment]
1.73 has been out for a while:  http://jcenter.bintray.com/com/beust/jcommander/1.73/
