### ISSUE TITLE
Does Not Support "--param=value" Flavor

### ISSUE THREAD

**Issue by seamlik** [cbeust/jcommander#432]
JCommander does not support "--param=value" flavor. For example:

```java
import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;

public class Main {

  private class Args {
    @Parameter(names = "--name")
    private String name;
  }

  public static void main(String[] args) {
    new Main().run();
  }

  private void run() {
    Args args = new Args();
    JCommander jc = JCommander.newBuilder().addObject(args).build();
    jc.parse("--name=test");
    System.out.println(args.name);
  }
}
```

By above I defined a parameter called `--name`. Turns out JCommander accepts `--test name` but not `--test=name`, as this program ends in error:

```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--name=test' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:887)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:705)
        at com.beust.jcommander.JCommander.parse(JCommander.java:312)
        at com.beust.jcommander.JCommander.parse(JCommander.java:291)
        at Main.run(Main.java:18)
        at Main.main(Main.java:12)
```

This has confused me quite much, since the official documentation suggests it supports this flavor by parsing `--author=cbeust` in [here](http://jcommander.org/#_more_complex_syntaxes_commands).

**Comment by Hubbitus** [comment]
According to description from you link you forgot `@Parameters(separators = "=")` on `Args` class:
```
import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;

public class Main {

    @Parameters(separators = "=")
    private class Args {
        @Parameter(names = "--name")
        private String name;
    }

    public static void main(String[] args) {
        new Main().run();
    }

    private void run() {
        Args args = new Args();
        JCommander jc = JCommander.newBuilder().addObject(args).build();
        jc.parse("--name=test");
        System.out.println(args.name);
    }
}
```

**Comment by seamlik** [comment]
@Hubbitus 

Your solution indeed worked. Sorry for being drowned in the ocean of javadoc, closing this now. Thank you!

**Comment by brandones** [comment]
This would seem like an extremely easy mistake to make as a user of a program. The user, when making this mistake, is presented with an error message that says something incomprehensible regarding the implementation specifics. When they see that, they have no choice but to give up.

It would be much better to catch this sort of thing with an error message like "Parameters must be separated with spaces." Of course, even better would be to make the default behavior of this library more intuitive, by accepting both styles.
