### ISSUE TITLE
Determine required parameters based on main command

### ISSUE THREAD

**Issue by opensorceror** [cbeust/jcommander#436]
First of all, amazing work on JCommander! 😃 

I'm building a CLI parser that will have several main commands (`dfs`, `query`, etc). Each of these main commands will have certain parameters, all of which are *required*, but only for the **specified** main command. I'm finding this hard to implement using `ParametersDelegate`. If I annotate a parameter as `required`, JCommander throws an exception if it is not specified, even if the specified parameter is not related to the specified main command.

For example, suppose:
1. `dfs` has required parameters `--LOB` and `--project`.
2. `query` has required parameter `--driver`.

Now, if I specify `dfs --LOB X --project test`, I get an exception saying `--driver` has not been specified, even though `--driver` has nothing to do with `dfs`. 

How can I remedy this?

**Comment by Insomnia00** [comment]
what you can so is have is a main command and inside them contain the
command parameters. As such

**Comment by opensorceror** [comment]
Thanks, I ended up doing it this way. :smile
