### ISSUE TITLE
PositiveInteger validator fails to throw exception for 0 value

### ISSUE THREAD

**Issue by xmiao2** [cbeust/jcommander#438]
https://github.com/cbeust/jcommander/blob/9f251415677106b683e4bbaf82123f0e5930cdce/src/main/java/com/beust/jcommander/validators/PositiveInteger.java#L34

Currently the class is more like a NonNegativeInteger validator. Shouldn't it be `n <= 0`?

Wanted to know @cbeust's thoughts before making pull requests.

Regards,
James

**Comment by cbeust** [comment]
Mmmh... not sure, I think it's fine as it is.

**Comment by shaburov** [comment]
@cbeust, xmiao2 is right in his reasoning.
[A positive number is a number that is bigger than zero.](https://simple.wikipedia.org/wiki/Positive_number)

**Comment by cbeust** [comment]
Fixing this could potentially break users, so closing this.
