### ISSUE TITLE
Release with latest code not available.

### ISSUE THREAD

**Issue by Chiranjivee** [cbeust/jcommander#456]
Hi,

I am on version 1.72 but just wanted to check when can we have the new release containing the latest code. As I need to use the IUsageFormatter to provide my custom usage implementation.

Thanks

**Comment by ebayedq** [comment]
Same here, this is really the only feature I'm missing right now

**Comment by 3flex** [comment]
1.75 was released a few days ago: https://bintray.com/cbeust/maven/jcommander/1.75

**Comment by asashour** [comment]
I am afraid it is not in maven central repository: https://search.maven.org/search?q=a:jcommander

**Comment by cbeust** [comment]
Fixed, 1.75 now available on Maven Central:  https://search.maven.org/artifact/com.beust/jcommander/1.75/jar
