### ISSUE TITLE
Project help wanted?

### ISSUE THREAD

**Issue by mkarg** [cbeust/jcommander#466]
@cbeust Cedric, according to the Github statistics, your project is stale since one year. While there are recent issues and PRs, no commits have been pushed for one full year. Do you need project help? Our company could chime in and manage the project for you if you like.

**Comment by garydgregory** [comment]
Closed with no comment?

**Comment by cbeust** [comment]
I thought that was spam. Who would offer to manage an open source project for someone else, seriously? And "our company"? Without giving the name?

Super fishy to me.

**Comment by mkarg** [comment]
@mkarg Actually I am not a spammer and this is not fishy. We need to ensure that JCommander is actively maintained as we started to use it in our long term maintainted products. In the past twelve months [Github reported zero activity](https://github.com/cbeust/jcommander/graphs/contributors?from=2018-03-01&to=2019-03-01&type=c). One option would be forking it, another would be waiting for someone reactivating your original project, a third would be to be that one. I cannot see what is fishy in our offer, as you could [simply google me](http://lmgtfy.com/?q=markus+karg+java) or just open [my Github profile](https://github.com/mkarg)? What benefit do you have from giving our company name? It is [ProSeS BDE GmbH](https://www.quipsy.de/index.php/en/) and you certainly don't know it; I am co-lead of the QUIPSY(R) division there. We already manage open source projects completely or in part for "others" at e. g. [Eclipse JAX-RS](https://github.com/eclipse-ee4j/jaxrs-api/graphs/contributors) where I am rather active as a manager (I was member of the JCP expert group JSR 311, 339, 370 and am a Eclipse JAX-RS Committer and Eclipse Jersey Contributor). So less fishy now? Reopen? Or planning to actively maintain this project again on your own?

**Comment by cbeust** [comment]
Thanks for the clarifications, @mkarg. I was mistaken, but you have to admit your initial phrasing was less than clear.

JCommander is active and I monitor and address issues diligently as they come, as you can see right here by me addressing your issue within just a few hours of you opening it.

There's just nothing pressing that needs to be done for JCommander right now, that I know of anyway, so little reason for any activity. It's quite possible that JCommander has reached a point where it's fitting all the requirements of its users and doesn't require much more work beyond its current status.

If you have bug fixes or feature requests, feel free to file issues and I'll consider them as diligently as I'm doing this one.

**Comment by mkarg** [comment]
Good to hear that, but I wonder how that fits with currently 71 open issues and 22 open PRs, some of them as old as created in 2013?

**Comment by Insomnia00** [comment]
You took on an open source project, you should know the risk. To be honest he did great on his own up to now, I really hope not to see other dev trying to take over just because their project is dependent on this open source project. I can feel like it is his flesh and blood right here.

**Comment by cbeust** [comment]
Thanks, @Insomnia00.

For what it's worth, I created TestNG in 2004 and still maintain it to this day. I don't easily give up and I'm happy to help users.

As for the open issues, @mkarg, they are more of a reflection that I don't have enough time to curate them and close them and an abandonment of the project. If these issues are still open, it's probably because either they are making suggestions that don't align with my vision of JCommander or because they are not urgent enough or too specific to be worth considering.

Again, @mkarg, if you have anything specific you'd like to discuss, I'm happy to. But pointing to a backlog of issues as a sign of abandonment of an open source project and then proposing to take it over without any context makes me wonder if you understand how open source works, especially when it's managed by a lonely developer with a day job, a family, and hobbies.

**Comment by mkarg** [comment]
Don't get me wrong, we just have to assure that our upstreams are vital, and Github statistics are pretty well suited for this usually (maybe not in this particular project apparently). Be sure, we are in the software business for 30+ years, about 20 of them in open source, so we know how to asses potential risks. Exactly Cedric's last line about being managed as a hobby is what matches our impression. Anyways, good luck for the future.  If you need us, we are here. :-)

**Comment by cbeust** [comment]
@mkarg, thanks.

You don't need my permission nor taking over the project: if you, or your team, or your company, wants to see new features or bug fixes, file issues or send pull requests.

It's really that easy.

**Comment by mkarg** [comment]
@cbeust Done: #467 #468 ;-)

In fact the question is what you prefer: Issues or PRs? We could also fork and file PRs if this is what you prefer instead of simply suggesting new features.

**Comment by cbeust** [comment]
Pull requests are obviously preferred, ideally with an accompanying new test (although these two issues you outlined probably don't warrant a test).

**Comment by mkarg** [comment]
@cbeust The last release is two years old, so some interesting bug fixes have gathered in `master` meanwhile (in particular enabling converters on the main parameter). What is the schedule for the next release?

**Comment by cbeust** [comment]
1.75 is released.
