### ISSUE TITLE
@Param(default = )

### ISSUE THREAD

**Issue by mkarg** [cbeust/jcommander#471]
When using complex parameter types, often the defaults printed by `usage()` are unreadable. For example, the class of the parameter does not overwrite `toString()` so it prints just a hash code. Often these classes are `final` so the application programmer cannot fix this. In other cases, the application programmer might like to replace the simple telling of the default by a more elaborate wording, e. g. *Default: platform dependent standard value*.

In these cases the application programmer needs to be able to override JCommander's default behavior.

The most intuitive solution would be `@Parameter(default = "platform dependent standard value")`.

**Comment by fsd654qyl** [comment]
I would like to try on this.
