### ISSUE TITLE
Help Option for command which has required options

### ISSUE THREAD

**Issue by khmarbaise** [cbeust/jcommander#49]
I would like to define a help option for commands. I created a [main command](https://github.com/khmarbaise/cli-test/blob/master/src/main/java/com/soebes/cli/cli_test/MainCommand.java) class which has an help option so i can do the following:

<pre>name --help</pre>

So now i define [some commands](https://github.com/khmarbaise/cli-test/blob/master/src/main/java/com/soebes/cli/cli_test/MergeCommand.java) like the following:

<pre>name XYZ [options]</pre>

The options for the command XYZ now contain required flag for example --file (what ever).
The result from that it is not possible to have a help option for the XYZ command (ok i can define one, but i can't parse it, cause it would produce a ParameterException: The following options are required: --file ... first).
An example of my problem can be found in the project [cli-test](https://github.com/khmarbaise/cli-test/blob/master/src/test/java/com/soebes/cli/cli_test/MergeCommandTest.java#L82)
The question is might it be a good idea to create a special annotation @Parameter(help = true...) to make it possible to parse the --help before an exception will be thrown. May be there are other better solutions as well?

**Comment by jeremysolarz** [comment]
Closing, since this functionality is now included.
