### ISSUE TITLE
Cannot use @-syntax in conjunction with arguments starting with literal @

### ISSUE THREAD

**Issue by c-kunz** [cbeust/jcommander#501]
# Description

One cannot use the [`@`-syntax](https://jcommander.org/#_syntax) in conjunction with parameters that may contain a literal `@` at the beginning.

## Steps to reproduce:

In this repository: https://github.com/c-kunz/jcommander-conflicting-at-syntax

```bash
git clone https://github.com/c-kunz/jcommander-conflicting-at-syntax
cd jcommander-conflicting-at-syntax
mvn clean package
java -jar target/demo-jar-with-dependencies.jar -password @X
```

## Expected result

JCommander is able to parse the argument beginning with the literal `@` while also being able to parse additional arguments using the `@`-syntax.

## Actual result

JCommander interprets the argument starting with a literal `@` as a file containing additional arguments ([`@`-syntax](https://jcommander.org/#_syntax)):

`Exception in thread "main" com.beust.jcommander.ParameterException: Could not read file X: java.nio.file.NoSuchFileException: X`

## Workaround

One has to settle for the following workaround, basically disabling the `@`-syntax altogether:

```java
JCommander cli = ...
cli.setExpandAtSign(false);
```

## Proposal

Since this is an either-or situation, either disabling `@`-syntax or prohibiting arguments starting with a literal `@`, it would be nice to be able to **for example** specify parameters that lookup additional arguments in a file or specify parameters that ignore leading `@` signs.

**Comment by c-kunz** [comment]
Issue https://github.com/cbeust/jcommander/issues/462 might be related:

> So... there isn't any externally defined concept of the `@file`?

**Comment by mkarg** [comment]
# Proposed Solution

JCommander should have a new option which allows using `@` as part of parameter *values* but still recognizes it as file name prefix when used in parameter *names*. Hence, the old behavior would be the default, but new applications could opt-in to the new bahvior.

**Comment by mkarg** [comment]
See also #330.

**Comment by HennyNile** [comment]
Hello, I think @-syntax is a new feature that allows user to write parameter vlaues in a file and the progarm will read them form the file. And as @c-kunz  has mentioned, you can choose if you use @-syntax or not by setting the value of variable JCommander.Options.expandAtSign which is a  private variable. 
The only problem I think is if you use JCommander.newBuilder() to create a Builer and use the Builer to set value of parameters, you can't set JCommander.Options.expandAtSign because there is no public method in Options which set values of JCommander.Options.expandAtSign. Then I will try to fix this problem.

**Comment by HennyNile** [comment]
Hello, I want to try to work on this issue. 
I plan to modify the judge rule of @-syntax which is inspired by that file name can not start with / in windows and linux.

**Comment by mkarg** [comment]
@c-kunz Thank you for reporting this bug! It was fixed some minutes ago, and will be contained in either 1.83.1 or 1.84 (whatever comes first).
