### ISSUE TITLE
ECCN for jcommander

### ISSUE THREAD

**Issue by akshayrb9** [cbeust/jcommander#506]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for jcommander if it applies. Can you please let me know the ECCN ?

**Comment by mkarg** [comment]
(1) This is not a user forum but a tracker for bugs and enhancement requests. The user forum is found at: https://groups.google.com/g/jcommander.

(2) ECCNs apply to products of *US* origin. This is an *international* open source project. Hence the project itself does not manage things like ECCNs. It is up to the specific exporter to have an ECCN.
