### ISSUE TITLE
Default value display in usage()

### ISSUE THREAD

**Issue by khmarbaise** [cbeust/jcommander#51]
I have a command which has an option --torev 

```
@Parameter(names = {"--torev"}, description = "The revision to which the scanning process will run.", converter = RevisionConverter.class)
private int toRev;
```

Based on the RevisionConverter class i can give on the command line:

   command --torev HEAD

But if i printout the usage:

   --torev         The revision to which the scanning process will run. (default: -1)

Does exist a god way to show the HEAD for the default instead of the -1?

**Comment by jeremysolarz** [comment]
As a work-around one could define revision as String assign a default value and cast the value to `Long/Integer` once needed.

```
@Test
  public void testDefaultValue(){
    class A {
      @Parameter(names = {"--torev"}, description = "The revision to which the scanning process will run.")
      private String toRev = "HEAD";
    }

    A a = new A();
    new JCommander(a).usage();
}
```
