### ISSUE TITLE
New release with backwards compatibility fixes.

### ISSUE THREAD

**Issue by yeroc** [cbeust/jcommander#534]
Is there any change a new release could be created that includes #523?  This would be extremely helpful.

Thanks!

**Comment by yeroc** [comment]
@cbeust Is there anyway I can help on this?

**Comment by mkarg** [comment]
@yeroc Please try out latest JCommander 1.83 and confirm whether your reported issue is resolved. Thanks.

**Comment by yeroc** [comment]
@mkarg Yes, this ticket is resolved with the 1.83 release.  Thanks!
