### ISSUE TITLE
How to add command line parameter dependency with JCommander?

### ISSUE THREAD

**Issue by simonjhy** [cbeust/jcommander#536]
How to add command line parameter dependency between multiple parameters using JCommander?

**Comment by mkarg** [comment]
This will be the answer once it got merged: https://github.com/cbeust/jcommander/pull/542 :-)

**Comment by mkarg** [comment]
@simonjhy Please try out latest JCommander 1.83 and confirm whether your reported issue is solved. Thanks.

**Comment by mkarg** [comment]
@simonjhy As you did not respond I assume this issue got fixed using 1.83, so I am closing this ticket hereby.
