### ISSUE TITLE
Please document your gpg keys

### ISSUE THREAD

**Issue by yeikel** [cbeust/jcommander#541]
We use [Dependency Verification](https://docs.gradle.org/current/userguide/dependency_verification.html) and currently there is no documentation stating which keys are safe

Could you please document this?

For example,`1.81` [ was signed](https://repo1.maven.org/maven2/com/beust/jcommander/1.81/jcommander-1.81.jar.asc) using [dcba03381ef6c89096acd985ac5ec74981f9cda6](https://keyserver.ubuntu.com/pks/lookup?search=dcba03381ef6c89096acd985ac5ec74981f9cda6&fingerprint=on&op=index)

But `1.82` [was signed](https://repo1.maven.org/maven2/com/beust/jcommander/1.82/jcommander-1.82.jar.asc) is using a [22E44AC0622B91C3](https://keyserver.ubuntu.com/pks/lookup?search=22E44AC0622B91C3&fingerprint=on&op=index)

Here are some examples of other projects documenting what key they use to sign their artifacts.

https://github.com/qos-ch/slf4j/blob/master/SECURITY.md#verifying-contents
https://square.github.io/okhttp/security/security/#verifying-artifacts
https://downloads.apache.org/logging/KEYS

**Comment by mkarg** [comment]
Since we release 1.83 with a different signing key, is this issue still and issue?

**Comment by yeikel** [comment]
> Since we release 1.83 with a different signing key, is this issue still and issue?

Is that expected key documented somewhere in the repo?

**Comment by mkarg** [comment]
> > Since we release 1.83 with a different signing key, is this issue still and issue?
> 
> Is that expected key documented somewhere in the repo?

No it is not. According to https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key it should be found on a keyserver.

**Comment by yeikel** [comment]
> > > Since we release 1.83 with a different signing key, is this issue still and issue?
> > 
> > 
> > Is that expected key documented somewhere in the repo?
> 
> No it is not. According to https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key it should be found on a keyserver.

Yes, but there are multiple key servers and there should be a way to link it back to the project. The `Security.md` file is a good place to document that back in the repo. 

For example, see this : https://github.com/qos-ch/slf4j/blob/master/SECURITY.md#verifying-contents

**Comment by mkarg** [comment]
Please find the GPG Signing Key for validation here: https://github.com/cbeust/jcommander/blob/master/SECURITY.md#gpg-signature-validation. 😃
