### ISSUE TITLE
Global parameter validation documentation is not deployed to jcommander.org

### ISSUE THREAD

**Issue by jontmy** [cbeust/jcommander#547]
PR #542 (which implements #539) which introduced `IParametersValidator` included its documentation for it, but it is not deployed to the JCommander website.

This is the current paragraph for the global parameter validation section that is live:
<img width="1021" alt="Screenshot 2022-11-02 at 19 55 05" src="https://user-images.githubusercontent.com/50949210/199483605-a6393a11-0171-465d-9207-2e283d8fe76f.png">

The documentation which #542 added is linked here: [https://github.com/cbeust/jcommander/blob/master/docs/index.adoc#global-parameter-validation](https://github.com/cbeust/jcommander/blob/master/docs/index.adoc#global-parameter-validation).

**Comment by mkarg** [comment]
The reason simply is that the latest published jCommander is 1.82, which does not contain that feature.

@cbeust I'd like to propose publishing jCommander 1.83 in Q1/2023, WDYT?

**Comment by mkarg** [comment]
Closing this issue, as JCommander was published on Maven Central in 2024 (see https://repo1.maven.org/maven2/org/jcommander/jcommander/1.83/).
