### ISSUE TITLE
Unknown class files in released jar

### ISSUE THREAD

**Issue by npetzall** [cbeust/jcommander#553]
Downloading version 1.82 from Maven Central
https://repo1.maven.org/maven2/com/beust/jcommander/1.82/jcommander-1.82.jar

Opening this file in 7Zip reveals that there is a sibling package to `jcommander` named `ah`

![image](https://user-images.githubusercontent.com/4175123/227747213-72b684dd-390c-4d76-aeb8-626721ba5674.png)

`ah` contains 2 class-files. `A.class` and `Pair.class`

![image](https://user-images.githubusercontent.com/4175123/227747282-51cd9080-3f60-4f73-961a-3eab0817cfe1.png)

I'm unable to track down where these classes come from, and why they are there. Can you advice?

They are not present in version 1.81

**Comment by mkarg** [comment]
Thank you for reporting this issue! It seems it meanwhile was fixed, as I could not see that files in latest 1.83. :-)

**Comment by npetzall** [comment]
@mkarg I think it was related to the build environment for that release.

New version is different group id on maven right?
