### ISSUE TITLE
Escaping paramater content

### ISSUE THREAD

**Issue by priand** [cbeust/jcommander#556]
I need to pass a parameter that contains some characters that need to be escaped. For example, `command 'I'm the \"walrus\""`, where the actual parameter value is `I'm the "walrus"`. Is there a way to do this?
bash, for example, allow the use of escaped character. See: https://unix.stackexchange.com/questions/30903/how-to-escape-quotes-in-shell. I didn't find anything equivalent in JCommander.

**Comment by mkarg** [comment]
@priand As you did not respond to the last comment I assume my claim was correct, so I am closing this ticket now.
