### ISSUE TITLE
MainParameter class is not public so it cannot be used when creating a custom IUsageFormatter class

### ISSUE THREAD

**Issue by JaumeRibas** [cbeust/jcommander#559]
I tried copying the implementation of the DefaultUsageFormatter to customize it and it gives a compile error because it references the MainParameter class which is not public.

**Comment by mkarg** [comment]
@JaumeRibas I assume you mean https://github.com/cbeust/jcommander/blob/2d3fc624514fd7ca9e99dd5b2b06ab274495ebb6/src/main/java/com/beust/jcommander/JCommander.java#L67

Could you please provide a PR that makes the class public and that proofs the usefulness of doing so? Thanks.

**Comment by JaumeRibas** [comment]
Whichever you think is best, as long as people can replicate and tweak the functionality in the DefaultUsageFormatter class.
Thanks

**Comment by mkarg** [comment]
I think we should go with the interface. Will you provide a PR?

**Comment by JaumeRibas** [comment]
Sure, I'll try. It's time I learn.
