### ISSUE TITLE
Invalid module descriptor error with JCommander in Eclipse

### ISSUE THREAD

**Issue by mRcOol7** [cbeust/jcommander#588]
I'm encountering an error when trying to run a Java project using JCommander in Eclipse.
**Error Message:**
Error occurred during initialization of boot layer java.lang.module.FindException: Unable to derive module descriptor for C:\Users\HP.p2\pool\plugins\com.beust.jcommander_1.78.0.jar Caused by: java.lang.IllegalArgumentException: com.beust.jcommander.1.78.0: Invalid module name: '1' is not a Java identifier

**Comment by mkarg** [comment]
Please try with latest JCommander: 
```pom.xml
<dependency>
    <groupId>org.jcommander</groupId>
    <artifactId>jcommander</artifactId>
    <version>2.0</version>
</dependency>
```

**Comment by mkarg** [comment]
@mRcOol7 Does it work with JCommander 2.0?

**Comment by mkarg** [comment]
@mRcOol7 Kindly asking to reply to my question asked on November 1st. Thanks.

**Comment by mRcOol7** [comment]
Yes it's working

**Comment by mkarg** [comment]
Thanks for answering! :-)
