### ISSUE TITLE
Password option behaviour is unintuitive and inflexible

### ISSUE THREAD

**Issue by rodionmoiseev** [cbeust/jcommander#70]
The following I find unintuitive and inflexible:
1. The current password interface does not seem to provide any way to specify the password as an argument. (e.g. -pass=secret). A way to set the password in command line or to read it from some `@passwd.txt` would be nice.
2. If password has `required=true` set, then the user is forced to pass the `--pass` argument just to get a password prompt on the screen.  If the password is required there should be no need to specify `--pass` on the command line.

In fact, number 2. applies to all boolean options with `required=true` set. It does not really make sense to have required boolean options, unless the user can do something like `--debug=false`

Back to the point, I'd like to propose an interface like this:
- Add a new annotation for passwords, let's say `@PasswordParameter`. 
  - `@PasswordParameter(names = {"-p", "--pass"})` behaves like a standard `String` option (i.e. has arity of 1).
  - Additionally, `@PasswordParameter(flags = {"--prompt"})` behaves like the current implementation (i.e. has arity of 0).
- If password field is optional (default), then passing `-p=secret` would get the password from cmd, and `--prompt` would ask for password in the console. If no options specified not password is set and the program proceeds as usual.
- If password field is required, then specifying any options on the cmd behaves the same as when it's optional. If no options are specified, no error is generated and password is retrieved from the prompt.

The `@PasswordParameter` annotation will have all the same fields as in standard `@Parameter`, except `password` and with an additional `String[] flags() default {}`.

**Comment by jeremysolarz** [comment]
@cbeust no action for a long time. I guess with fixing the password prompt as requested in #195 we have covered a lot of use cases.
