### ISSUE TITLE
Required options with default values not found

### ISSUE THREAD

**Issue by hsiliev** [cbeust/jcommander#95]
I have implemented IDefaultProvider for my commands, although its getDefaultValueFor is called, JCommander.parse still tries to look for required options in the command line arguments.

I think the behavour should be changed to take into account the fact that there is already assigned value for a required option nevertheless the command line arguments do not have this overriden.

**Comment by jonmclean** [comment]
Issue still exists in the latest version.  It would be nice to apply shuwada's patch to master.

**Comment by hedgerocker** [comment]
+1

**Comment by cbeust** [comment]
Fixed in 1.55. Thanks @shuwada !
